#!/bin/sh
#
# Copyright (C) 2015-2016 DD-WRT shadowsocks
# Copyright (C) 2015-2016 Jason Lin <wojiaolinmu008@gmail.com>
# --------------------------------------------------------------------------------------------------------
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
# --------------------------------------------------------------------------------------------------------
#

# Debug
#set -x

# opkg source site
OPKG_SITE="http://entware.mirrors.ligux.com/binaries"

# Architecture
ARCH="armv7"

# SMTP server (EP:"smtp.gmail.com")
SMTP="smtp.163.com"
# Send E-mail Username
username=""
# Send E-mail password
password=""
# Sender E-mail
FROM=""
# E-mail Subject
TITLE="ShadowSocks"
# Content of E-mail
CONTENT="Your tools running over the wall!"
# Target E-mail address
TO=""

# ADBYBY ad filter
adbyby_filter=0
adbyby_filter_global=0

# ADBYBY_FILTER_RULES
adbyby_dns="http://entware.mirrors.ligux.com/adbyby_dns/adbyby_dns"

# Check DNS
check_dns=0

READ="\033[31;1m"
BOLD="\033[42;1m"
NORM="\033[0m"
ansi_red="\033[1;31m";
ansi_white="\033[1;37m";
ansi_green="\033[1;32m";
ansi_yellow="\033[1;33m";
ansi_blue="\033[1;34m";
ansi_bell="\007";
ansi_blink="\033[5m";
ansi_std="\033[m";
ansi_rev="\033[7m";
ansi_ul="\033[4m";
INFO="$BOLD INFO: $NORM"
WARNING="$READ WARNING: $NORM"
MOUNT="$ansi_white MOUNT: "
DEPENDENCE="$ansi_white DEPENDENCE: "
PLATFORM="$ansi_white PLATFORM: "
PACKAGES="$ansi_white PACKAGES: "
SHADOWSOCKS="$ansi_white SHADOWSOCKS: "
START_SCRIPT="$ansi_white START_SCRIPT: "
ShadowSocks_Account="$ansi_white ShadowSocks_Account: "
ss_switch="$ansi_white ss_switch: "
update_scr="$ansi_white update_scr: "
backup="$ansi_white backup: "

# You can mount the partition path editing (EP:"/jffs" or "/tmp/mnt/sda1" )
PREFIX=/jffs
SCRIPT_DIR=$(dirname ${0})
SCRIPT_DIR=$(cd ${SCRIPT_DIR} && pwd)

# Time
DATE=$(date "+%Y-%m-%d %H:%M:%S")

# Schduler
CHECK=/opt/etc

# Link
ops_list="http://entware.mirrors.ligux.com/opslist/opslist.conf"
china_routing_list="http://entware.mirrors.ligux.com/apnic/delegated-apnic-latest"
china_domain_list="http://entware.mirrors.ligux.com/dnsmasq-china-list/accelerated-domains.china.conf"
china_google_list="http://entware.mirrors.ligux.com/dnsmasq-china-list/google.china.conf"

# alias of iptables
IPT="/usr/iptables/iptables -t nat"

case ${1} in

-su | --set_up)
	DECIVE=$(cat /proc/cpuinfo | grep "ARMv7" | grep -v "grep")
	if [ -z "$DECIVE" ]; then
		echo -e -n $PLATFORM
		sleep 1
		echo -e "$ansi_red ERROR. $ansi_std"
		echo -e $WARNING $BOLD This script is not suitable for the platform,can not continue.$NORM 
		exit 0
	else
		if [ ! -d "$PREFIX/shadowsocks" ]; then
			echo -e $INFO "Creating in..."
			entware() {
				cd $PREFIX;wget -t0 $OPKG_SITE/$ARCH/backup/entware_backup.tar.gz
				sha1sum_entware="ffc285b0c4ded845c499508b365394ed77b682c1"
				checksum=`sha1sum $PREFIX/entware_backup.tar.gz | sed "s/  .*//"`
				if [ ! "$sha1sum_entware" == "$checksum" ]; then
					echo "$ansi_red entware-ng installation failed $ansi_std"
					exit 0
				fi
				tar -zxvf entware_backup.tar.gz
				[ -f $PREFIX/entware_backup.tar.gz ] && rm -rf $PREFIX/entware_backup.tar.gz
			}
			entware
			cd /tmp/root
			mkdir -p $PREFIX/shadowsocks
			cp $SCRIPT_DIR/shadowsocks $PREFIX/shadowsocks
			mount -o bind $PREFIX/opt /opt
			/opt/bin/opkg update
			if [ -e $SCRIPT_DIR/chinadns* -a -e $SCRIPT_DIR/diff* -a -e $SCRIPT_DIR/pcap-dns* -a -e $SCRIPT_DIR/pdns* -a -e $SCRIPT_DIR/shadowsocks-libe* -a -e $SCRIPT_DIR/dnscryp* ]; then
				cd $SCRIPT_DIR && opkg install --force-checksum china* pdnsd* pcap* shadowsocks-libe* diff* dnscry*
				echo -e "$ansi_green SHADOWSOCKS script installed successfully! $ansi_std"
				sleep 5
				ln -s $PREFIX/shadowsocks/shadowsocks /opt/bin
			else
				echo -e "$ansi_red You do not import the entire IPK! $ansi_std"
				exit 0
			fi
		else
			echo -e "$ansi_yellow SHADOWSOCKS already installed! $ansi_std"
		fi
		echo -e -n $PLATFORM
		sleep 1
		echo -e "$ansi_green PASS. $ansi_std"
	fi

	autorun=/opt/etc/init.d/auto.run
	if [ ! -f "$autorun" ]; then
		echo "#!/bin/sh" >> $autorun
		echo >> $autorun
		echo -e "mount -o bind $PREFIX/opt /opt" >> $autorun
		echo "/opt/bin/shadowsocks -m" >> $autorun
		echo "/opt/bin/shadowsocks -S" >> $autorun
		echo "sleep 1" >> $autorun
		echo "/opt/bin/shadowsocks -r" >> $autorun
		echo "stopservice cron && startservice cron" >> $autorun
		echo >> $autorun

		sleep 1
		chmod +x $autorun
		ln -s $autorun /opt/bin
	fi

	if [ -d "$PREFIX/shadowsocks" ]; then
		echo -e -n $SHADOWSOCKS
		sleep 1
		echo -e "$ansi_green PASS. $ansi_std"
	else
		echo -e -n $SHADOWSOCKS
		sleep 1
		echo -e "$ansi_red ERROR. $ansi_std"
		rm -rf $PREFIX/opt
		echo -e $WARNING $BOLD"Please install the SHADOWSOCKS script."$NORM
		exit 0
	fi

	if [ "`ls -A /opt`" = "" ]; then
		echo -e -n $MOUNT
		sleep 1
		echo -e "$ansi_red ERROR. $ansi_std"
		rm -rf $PREFIX/opt
		echo -e $WARNING $BOLD"OPT directory does not mount."$NORM
		exit 0
	else
		echo -e -n $MOUNT
		sleep 1
		echo -e "$ansi_green PASS. $ansi_std"
	fi

	BIN=/opt/bin
	SBIN=/opt/sbin
	echo -e "chinadns \ndiff \ndnscrypt-proxy \nPcap_DNSProxy \npdnsd-ctl \nss-redir" > /var/log/find.txt
	cd $BIN
	if [ ! -f chinadns -o ! -f Pcap_DNSProxy -o ! -f ss-redir -o ! -f pdnsd-ctl -o ! -f diff -o ! -f dnscrypt-proxy ]; then
		ls -1 chinadns Pcap_DNSProxy ss-redir pdnsd-ctl diff dnscrypt-proxy > /var/log/find_N.txt
	else
		ls -1 chinadns Pcap_DNSProxy ss-redir pdnsd-ctl diff dnscrypt-proxy > /var/log/find_N.txt
	fi
	cd /

	find $BIN/chinadns $BIN/Pcap_DNSProxy $BIN/ss-redir $BIN/pdnsd-ctl $BIN/diff $BIN/dnscrypt-proxy &> /dev/null;echo $? > /var/log/diff.txt
	DIFF=`sed -n '1p' /var/log/diff.txt`
	diff -w /var/log/find.txt /var/log/find_N.txt | grep \^\< > /var/log/diff_show.txt
	if [ "$DIFF" == "0" ]; then
		echo -e -n $DEPENDENCE
		sleep 1 
		echo -e "$ansi_green PASS. $ansi_std"
	else
		if [ ! -e $BIN/chinadns -a ! -e $BIN/diff -a ! -e $BIN/Pcap_DNSProxy -a ! -e $BIN/pdnsd-ctl -a ! -e $BIN/ss-redir -a ! -e $BIN/dnscrypt-proxy ]; then
			echo -e $DEPENDENCE
			sleep 1
			echo -e "$ansi_red ERROR. $ansi_std"
			echo -e "$WARNING \n$BOLD Please install the following software:"$NORM
			rm -rf $PREFIX/opt
			echo -e $ansi_white"shadowsocks-libev \nchinadns \npdnsd \npcap-dnsproxy \ndiffutils \ndnscrypt-proxy"$ansi_std
			exit 0
		else
			echo -e $DEPENDENCE
			sleep 1
			echo -e "$ansi_red ERROR. $ansi_std"
			echo -e "$WARNING \n$BOLD Please install the following software:"$NORM
			rm -rf $PREFIX/opt
			cat /var/log/diff_show.txt
			exit 0
		fi
	fi

	if [ -f "$autorun" ]; then
		echo -e -n $START_SCRIPT
		sleep 1
		echo -e "$ansi_green PASS. $ansi_std"
	fi

	yes_or_no() {
    		read -p "$1 ([y]es or [n]o): "
    		case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
        		y|yes) echo "yes" ;;
        		*)     echo "no" ;;
    		esac
	}

	echo "============================================"
	echo "Please input your shadowsocks account information:"
	read -p "(Your Server IP):" IP
	read -p "(Your Server Port):" port
	read -p "(Your Local Port):" PORT
	read -p "(Your Password):" password
	read -p "(Your Encryption Method):" method
	echo "============================================"
	echo "Please confirm your shadowsocks information:"
	echo -e "Your Server IP: \033[41;37m ${IP} \033[0m"
	echo -e "Your Server Port: \033[41;37m ${port} \033[0m"
	echo -e "Your Server Port: \033[41;37m ${PORT} \033[0m"
	echo -e "Your Password: \033[41;37m ${password} \033[0m"
	echo -e "Your Encryption Method: \033[41;37m ${method} \033[0m"
	echo "============================================"

	ping -q -w1 ${IP} | grep "PING" | sed -e "s;).*;;" -e "s;.*(;;" > /opt/var/log/resolvip_tmp.txt
	ping_ip() {
		ping -q -w1 ${IP} &> /dev/null
		return $?
	}

	ping_ip
	if [ ! "$?" = 0 ]; then
		echo -e "$WARNING You input an incorrect IP, please re-enter your: $ansi_white \nshadowsocks -su"$NORM
		exit 0
	fi

	server_ip=/opt/var/log/resolvip_tmp.txt

	get_server_ip() {
		cat <<-EOF | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}"
			$(cat ${server_ip=:/dev/null} 2>/dev/null)
	EOF
	}
	echo $(get_server_ip) > /opt/var/log/resolvip.txt
	sed -i '/^$/d' /opt/var/log/resolvip.txt
	if [ -s "/opt/var/log/resolvip.txt" ]; then
		RIP=`sed -n '1p' /opt/var/log/resolvip.txt`
		echo -e $INFO Creating shadowsocks config file...
		rm -f $CHECK/shadowsocks.json
		cat > $CHECK/shadowsocks.json <<-end
	{
    "server":"$RIP",
    "server_port":${port},
    "local_address":"0.0.0.0",
    "local_port":${PORT},
    "password":"${password}",
    "timeout":60,
    "method":"${method}"
	}
		end
		sed -i '11d' $CHECK/shadowsocks.json
	else
		echo -e "$WARNING Can not write the configuration information, please re-enter your: $ansi_white \nshadowsocks set_up"$NORM
		exit 0
	fi

	echo -e "$ansi_white You confirm shadowsocks information you filled out correctly?(y/N)$ansi_std"
	if [ "no" == $(yes_or_no) ]; then
		echo -e $INFO Re-setting...
  		echo -e $INFO Exiting...
		rm -f $CHECK/shadowsocks.json
		kill `ps | grep "shadowsocks" | grep -v "grep" | awk '{print $1}'`
	fi

echo -e $INFO "Please select Please choose the following programs:\n\
$BOLD##programs_1##:$NORM (ss-redir+gfwlist+pdnsd)\n\
$BOLD##programs_2##:$NORM (ss-redir+chnroutes+chinadns+pdnsd)\n\
$BOLD##programs_3##:$NORM (ss-redir+chnroutes+chinadns+dnscrypt-proxy)\n\
$BOLD##programs_4##:$NORM (ss-redir+chnroutes+pcap_dnsproxy)\n\
$BOLD##programs_5##:$NORM (ss-tunnel+chnroutes+chinadns)\n\
Your Choice:"
	read programs
	if [ $programs == "1" ];then
		echo -e "$BOLD Set programs_1..." $NORM
		sed -e "s/shadowsocks.json\"/shadowsocks.json\"/" -e "s/PROCS=ss-local/PROCS=ss-redir/" -i  $CHECK/init.d/S22shadowsocks
		sed -n 's/.*ver":"\(.*\)".*/\1/p' $CHECK/shadowsocks.json  > $PREFIX/opt/var/log/server.txt

		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S26pdnsd (start))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks
		sed -i 's/PROCS=ss-start/PROCS=ss-nat/;s/^ARGS=""/ARGS="-G"/' $CHECK/init.d/S99ss-rules 

		rm -f $CHECK/pdnsd.conf
		cat > $CHECK/pdnsd.conf <<-end
global {
perm_cache=2048;
cache_dir="/var/pdnsd";
run_as="nobody";
server_port = 1054;
server_ip = 127.0.0.1;
status_ctl = on;
query_method=tcp_only;
min_ttl=6h;
max_ttl=1w;
timeout=10;
}

server {
label= "google";
ip = 208.67.222.222;
port = 443;
root_server = on;
uptest= none;
}
		end

		$PREFIX/shadowsocks/shadowsocks -m
		$PREFIX/shadowsocks/shadowsocks -S
		$PREFIX/shadowsocks/shadowsocks -ug
		sleep 1
		$PREFIX/shadowsocks/shadowsocks -r

		nvram set time_zone="Asia/Shanghai"

		echo -e $INFO Configuring dnsmasq_custom...
		DNS_CUSTOM=`echo -e "min-cache-ttl=6000\ncache-size=10000\
		\nconf-dir=$PREFIX$CHECK/dnsmasq.d" | \
		sed -e 's/[\t]*//g' | \
		sed -e ''`
		nvram set dnsmasq_options="$DNS_CUSTOM"

		echo -e $INFO Configuring turn startup items and guard the capital...
		echo -e "$PREFIX/opt/etc/init.d/auto.run" > /var/log/scr_c.txt
		SCR=`sed -e '' /var/log/scr_c.txt`
		nvram set rc_startup="$SCR"

		echo -e $INFO Configuring crontab_custom...
		CRON=`echo -e "*/1 * * * * root /opt/bin/shadowsocks -c\
		\n*/30 * * * * root /opt/bin/clear" | \
		sed -e 's/[\t]*//g' | \
		sed -e ''`
		nvram set cron_jobs="$CRON"
		echo -e "echo \"\" > /var/log/shadowsocks_watchdog.log\
		\necho \"\" > /var/log/pdnsd_watchdog.log" \
		> /opt/bin/clear
		sed -i 's/[\t]*//g' /opt/bin/clear && \
		chmod -R 755 /opt/bin/clear
		nvram commit
		stopservice dnsmasq && \
			startservice dnsmasq			

		$PREFIX/shadowsocks/shadowsocks -b
		echo -e "$ansi_red Set successfully, please reboot the router. Found a Bug? Plea se report at https://github.com/houzi-/dd-wrt-shadowsocks/issues. $ansi_std"
		killall shadowsocks > /dev/null
	elif [ $programs == "2" ];then
		echo -e "$BOLD Set programs_2..." $NORM
		sed -e "s/shadowsocks.json\"/shadowsocks.json\"/" -e "s/PROCS=ss-local/PROCS=ss-redir/" -i  $CHECK/init.d/S22shadowsocks
		sed '4c PROCS=chinadns' $CHECK/init.d/S22shadowsocks > $CHECK/init.d/S24cn
		sed '5c ARGS="-p 5353 -c /opt/etc/chnroute.txt -s 114.114.114.114,127.0.0.1:1054"' $CHECK/init.d/S24cn > $CHECK/init.d/S24chinadns

		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S26pdnsd (start))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks
		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S24chinadns (start|restart))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks

		if [ -n "`nvram get wan_get_dns | sed 's/ /,/'`" ]; then
			CHINADNS=`nvram get wan_get_dns | awk '/^.*/{print $1}'`
			sed -i "s/^ARGS=\(.*\)114.114.114.114\(.*\)$/ARGS=\1$CHINADNS\2/" $CHECK/init.d/S24chinadns
		else
			CHINADNS=`cat /tmp/resolv.dnsmasq | awk '/^nameserver/{print $2}' | sed -n '1p'`
			sed -i "s/^ARGS=\(.*\)114.114.114.114\(.*\)$/ARGS=\1$CHINADNS\2/" $CHECK/init.d/S24chinadns
		fi

		rm -f $CHECK/init.d/S24cn
		chmod +x $CHECK/init.d/S2*

		sleep 1
		echo -e $INFO Creating pdnsd.conf file...
		rm -f $CHECK/pdnsd.conf
		cat > $CHECK/pdnsd.conf <<-end
global {
perm_cache=2048;
cache_dir="/var/pdnsd";
run_as="nobody";
server_port = 1054;
server_ip = 127.0.0.1;
status_ctl = on;
query_method=tcp_only;
min_ttl=6h;
max_ttl=1w;
timeout=10;
}

server {
label= "google";
ip = 208.67.222.222,208.67.220.220;
root_server = on;
uptest= none;
}
		end

		touch $PREFIX/shadowsocks/update.lock
		touch $PREFIX/shadowsocks/chnroutes.lock
		$PREFIX/shadowsocks/shadowsocks -m
		sleep 4
		$PREFIX/shadowsocks/shadowsocks -S
		sleep 2
		$PREFIX/shadowsocks/shadowsocks -r

		nvram set time_zone="Asia/Shanghai"

		echo -e $INFO Configuring dnsmasq_custom...
		DNS_CUSTOM=`echo -e "no-resolv\nno-poll\
		\nserver=127.0.0.1#5353\
		\nmin-cache-ttl=6000\ncache-size=10000\
		\nconf-dir=$PREFIX$CHECK/dnsmasq.d" | \
		sed -e 's/[\t]*//g' | \
		sed -e ''`
		nvram set dnsmasq_options="$DNS_CUSTOM"
		stopservice dnsmasq && \
			startservice dnsmasq

		echo -e $INFO Configuring turn startup items and guard the capital...
		echo -e "$PREFIX/opt/etc/init.d/auto.run" > /var/log/scr_c.txt
		SCR=`sed -e '' /var/log/scr_c.txt`
		nvram set rc_startup="$SCR"
		nvram commit

		echo -e $INFO Configuring crontab_custom...
		CRON=`echo -e "*/1 * * * * root /opt/bin/shadowsocks -c\
		\n*/30 * * * * root /opt/bin/clear" | \
		sed -e 's/[\t]*//g' | \
		sed -e ''`
		nvram set cron_jobs="$CRON"
		echo -e "echo \"\" > /var/log/shadowsocks_watchdog.log\
		\necho \"\" > /var/log/chinadns_watchdog.log\
		\necho \"\" > /var/log/pdnsd_watchdog.log" \
		> /opt/bin/clear
		sed -i 's/[\t]*//g' /opt/bin/clear && \
		chmod -R 755 /opt/bin/clear
		nvram commit

		rm -f $PREFIX/shadowsocks/update.lock
		rm -f $PREFIX/shadowsocks/chnroutes.lock
		$PREFIX/shadowsocks/shadowsocks -b
		echo -e "$ansi_red Set successfully, please reboot the router. Found a Bug? Plea se report at https://github.com/houzi-/dd-wrt-shadowsocks/issues. $ansi_std"
		killall shadowsocks > /dev/null
	elif [ $programs == "3" ];then
		echo -e "$BOLD Set programs_3..." $NORM
		sed -e "s/shadowsocks.json\"/shadowsocks.json\"/" -e "s/PROCS=ss-local/PROCS=ss-redir/" -i  $CHECK/init.d/S22shadowsocks
		sed '4c PROCS=chinadns' $CHECK/init.d/S22shadowsocks > $CHECK/init.d/S24cn
		sed '5c ARGS="-p 5353 -c /opt/etc/chnroute.txt -s 114.114.114.114,127.0.0.1:1054,208.67.222.222:443"' $CHECK/init.d/S24cn > $CHECK/init.d/S24chinadns

		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S29dnscrypt-proxy (start))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks
		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S24chinadns (start|restart))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks

		if [ -n "`nvram get wan_get_dns | sed 's/ /,/'`" ]; then
			CHINADNS=`nvram get wan_get_dns | awk '/^.*/{print $1}'`
			sed -i "s/^ARGS=\(.*\)114.114.114.114\(.*\)$/ARGS=\1$CHINADNS\2/" $CHECK/init.d/S24chinadns
		else
			CHINADNS=`cat /tmp/resolv.dnsmasq | awk '/^nameserver/{print $2}' | sed -n '1p'`
			sed -i "s/^ARGS=\(.*\)114.114.114.114\(.*\)$/ARGS=\1$CHINADNS\2/" $CHECK/init.d/S24chinadns
		fi

		rm -f $CHECK/init.d/S24cn
		chmod +x $CHECK/init.d/S2*

		touch $PREFIX/shadowsocks/update.lock
		touch $PREFIX/shadowsocks/chnroutes.lock
		$PREFIX/shadowsocks/shadowsocks -m
		sleep 4
		$PREFIX/shadowsocks/shadowsocks -S
		sleep 2
		$PREFIX/shadowsocks/shadowsocks -r

		nvram set time_zone="Asia/Shanghai"

		echo -e $INFO Configuring dnsmasq_custom...
		DNS_CUSTOM=`echo -e "no-resolv\nno-poll\
		\nserver=127.0.0.1#5353\
		\nmin-cache-ttl=6000\ncache-size=10000\
		\nconf-dir=$PREFIX$CHECK/dnsmasq.d" | \
		sed -e 's/[\t]*//g' | \
		sed -e ''`
		nvram set dnsmasq_options="$DNS_CUSTOM"
		stopservice dnsmasq && \
			startservice dnsmasq

		echo -e $INFO Configuring turn startup items and guard the capital...
		echo -e "$PREFIX/opt/etc/init.d/auto.run" > /var/log/scr_c.txt
		SCR=`sed -e '' /var/log/scr_c.txt`
		nvram set rc_startup="$SCR"
		nvram commit

		echo -e $INFO Configuring crontab_custom...
		CRON=`echo -e "*/1 * * * * root /opt/bin/shadowsocks -c\
		\n*/30 * * * * root /opt/bin/clear" | \
		sed -e 's/[\t]*//g' | \
		sed -e ''`
		nvram set cron_jobs="$CRON"
		echo -e "echo \"\" > /var/log/shadowsocks_watchdog.log\
		\necho \"\" > /var/log/dnscrypt-proxy_watchdog.log\
		\necho \"\" > /var/log/chinadns_watchdog.log" \
		> /opt/bin/clear
		sed -i 's/[\t]*//g' /opt/bin/clear && \
		chmod -R 755 /opt/bin/clear
		nvram commit

		rm -f $PREFIX/shadowsocks/update.lock
		rm -f $PREFIX/shadowsocks/chnroutes.lock
		$PREFIX/shadowsocks/shadowsocks -b
		echo -e "$ansi_red Set successfully, please reboot the router. Found a Bug? Plea se report at https://github.com/houzi-/dd-wrt-shadowsocks/issues. $ansi_std"
		killall shadowsocks > /dev/null
	elif [ $programs == "4" ];then
		echo -e "$BOLD Set programs_4..." $NORM
		sed -e "s/shadowsocks.json\"/shadowsocks.json\"/" -e "s/PROCS=ss-local/PROCS=ss-redir/" -i  $CHECK/init.d/S22shadowsocks

		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S27pcap_dnsproxy (start))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks

		local_dns=`cat /etc/resolv.dnsmasq | awk '/^nameserver/{print $2}' | sed -n '1p'`
		sed -i "s/ 114.114.115.115:53/ $local_dns:53/" $CHECK/pcap-dnsproxy/Config.conf

		touch $PREFIX/shadowsocks/update.lock
		touch $PREFIX/shadowsocks/chnroutes.lock
		touch /var/log/pcap_dnsproxy.lock
		$PREFIX/shadowsocks/shadowsocks -m
		sleep 4
		$PREFIX/shadowsocks/shadowsocks -S
		sleep 2
		$PREFIX/shadowsocks/shadowsocks -r

		nvram set time_zone="Asia/Shanghai"

		echo -e $INFO Configuring dnsmasq_custom...
		DNS_CUSTOM=`echo -e "no-resolv\nno-poll\
		\nserver=127.0.0.1#5353\
		\nmin-cache-ttl=6000\ncache-size=10000\
		\nconf-dir=$PREFIX$CHECK/dnsmasq.d" | \
		sed -e 's/[\t]*//g' | \
		sed -e ''`
		nvram set dnsmasq_options="$DNS_CUSTOM"
		stopservice dnsmasq && \
			startservice dnsmasq

		echo -e $INFO Configuring turn startup items and guard the capital...
		echo -e "$PREFIX/opt/etc/init.d/auto.run" > /var/log/scr_c.txt
		SCR=`sed -e '' /var/log/scr_c.txt`
		nvram set rc_startup="$SCR"
		nvram commit

		echo -e $INFO Configuring crontab_custom...
		CRON=`echo -e "*/1 * * * * root /opt/bin/shadowsocks -c\
		\n*/30 * * * * root /opt/bin/clear" | \
		sed -e 's/[\t]*//g' | \
		sed -e ''`
		nvram set cron_jobs="$CRON"
		echo -e "echo \"\" > /var/log/shadowsocks_watchdog.log\
		\necho \"\" > /var/log/Pcap_DNSProxy_watchdog.log" \
		> /opt/bin/clear
		sed -i 's/[\t]*//g' /opt/bin/clear && \
		chmod -R 755 /opt/bin/clear
		nvram commit

		rm -f $PREFIX/shadowsocks/update.lock
		rm -f $PREFIX/shadowsocks/chnroutes.lock
		$PREFIX/shadowsocks/shadowsocks -b
		echo -e "$ansi_red Set successfully, please reboot the router. Found a Bug? Plea se report at https://github.com/houzi-/dd-wrt-shadowsocks/issues. $ansi_std"
		killall shadowsocks > /dev/null
	elif [ $programs == "5" ];then
		echo -e "$BOLD Set programs_5..." $NORM
		sed -e "s/shadowsocks.json\"/shadowsocks.json\"/" -e "s/PROCS=ss-local/PROCS=ss-redir/" -i  $CHECK/init.d/S22shadowsocks
		sed -e "s/shadowsocks.json\"/shadowsocks.json -b 0.0.0.0 -l 5300 -L 8.8.8.8:53 -u\"/" -e "s/PROCS=ss-redir/PROCS=ss-tunnel/" $CHECK/init.d/S22shadowsocks > $CHECK/init.d/S23ss-tunnel
		sed '4c PROCS=chinadns' $CHECK/init.d/S22shadowsocks > $CHECK/init.d/S24cn
		sed '5c ARGS="-p 5353 -l /opt/etc/chinadns_iplist.txt -c /opt/etc/chnroute.txt -s 114.114.114.114,127.0.0.1:5300"' $CHECK/init.d/S24cn > $CHECK/init.d/S24chinadns

		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S23ss-tunnel (start|restart))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks
		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S24chinadns (start|restart))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks

		if [ -n "`nvram get wan_get_dns | sed 's/ /,/'`" ]; then
			CHINADNS=`nvram get wan_get_dns | awk '/^.*/{print $1}'`
			sed -i "s/^ARGS=\(.*\)114.114.114.114\(.*\)$/ARGS=\1$CHINADNS\2/" $CHECK/init.d/S24chinadns
		else
			CHINADNS=`cat /tmp/resolv.dnsmasq | awk '/^nameserver/{print $2}' | sed -n '1p'`
			sed -i "s/^ARGS=\(.*\)114.114.114.114\(.*\)$/ARGS=\1$CHINADNS\2/" $CHECK/init.d/S24chinadns
		fi

		rm -f $CHECK/init.d/S24cn
		chmod +x $CHECK/init.d/S2*

		touch $PREFIX/shadowsocks/update.lock
		touch $PREFIX/shadowsocks/chnroutes.lock
		$PREFIX/shadowsocks/shadowsocks -m
		sleep 4
		$PREFIX/shadowsocks/shadowsocks -S
		sleep 2
		$PREFIX/shadowsocks/shadowsocks -r

		nvram set time_zone="Asia/Shanghai"

		echo -e $INFO Configuring dnsmasq_custom...
		DNS_CUSTOM=`echo -e "no-resolv\nno-poll\
		\nserver=127.0.0.1#5353\
		\nmin-cache-ttl=6000\ncache-size=10000\
		\nconf-dir=$PREFIX$CHECK/dnsmasq.d" | \
		sed -e 's/[\t]*//g' | \
		sed -e ''`
		nvram set dnsmasq_options="$DNS_CUSTOM"
		stopservice dnsmasq && \
			startservice dnsmasq

		echo -e $INFO Configuring turn startup items and guard the capital...
		echo -e "$PREFIX/opt/etc/init.d/auto.run" > /var/log/scr_c.txt
		SCR=`sed -e '' /var/log/scr_c.txt`
		nvram set rc_startup="$SCR"
		nvram commit

		echo -e $INFO Configuring crontab_custom...
		CRON=`echo -e "*/1 * * * * root /opt/bin/shadowsocks -c\
		\n*/30 * * * * root /opt/bin/clear" | \
		sed -e 's/[\t]*//g' | \
		sed -e ''`
		nvram set cron_jobs="$CRON"
		echo -e "echo \"\" > /var/log/shadowsocks_watchdog.log\
		\necho \"\" > /var/log/chinadns_watchdog.log" \
		> /opt/bin/clear
		sed -i 's/[\t]*//g' /opt/bin/clear && \
		chmod -R 755 /opt/bin/clear
		nvram commit

		rm -f $PREFIX/shadowsocks/update.lock
		rm -f $PREFIX/shadowsocks/chnroutes.lock
		$PREFIX/shadowsocks/shadowsocks -b
		echo -e "$ansi_red Set successfully, please reboot the router. Found a Bug? Plea se report at https://github.com/houzi-/dd-wrt-shadowsocks/issues. $ansi_std"
		killall shadowsocks > /dev/null
	fi
	;;

-m | --modules)
	echo -e -n "$ansi_white Load_Modules... "
	if [ ! "`lsmod | grep xt_set | wc -l`" -eq 1 ]; then
		if [ -f "/lib/modules/$(cat /proc/version | sed -e 's; (.*;;' -e 's;Linux version ;;')/xt_set.ko" ]; then
			modprobe xt_set
			if [ -f "/lib/modules/$(cat /proc/version | sed -e 's; (.*;;' -e 's;Linux version ;;')/xt_TPROXY.ko" ]; then
				modprobe xt_socket && \
				modprobe xt_TPROXY
			fi
		else
			modprobe ipv6
			modprobe nf_conntrack_ipv6
			insmod /opt/lib/modules/xt_TPROXY.ko
			insmod /opt/lib/modules/xt_socket.ko
			insmod /opt/lib/modules/xt_set.ko
		fi
	fi
	echo -e "            $ansi_green done. $ansi_std"
	;;

-S | --START)
	sed -n 's/.*ver": *"\(.*\)".*/\1/p' $CHECK/shadowsocks.json  > /var/log/server.txt

	[ ! -f /tmp/resolv.dnsmasq ] && \
		stopservice dnsmasq && \
			startservice dnsmasq

	check_dns() {
		old_dns=`cat $PREFIX/opt/etc/init.d/S24chinadns | sed -n "5p" | awk '/^.*/{print $6}' | sed -e 's/,127.*//' -e 's/,.*//'`
		new_dns=`cat /tmp/resolv.dnsmasq | awk '/^nameserver/{print $2}' | sed -n '1p'`
		if [ "$old_dns" == "$new_dns" ]; then
			echo "DNS is same!" > /var/log/check_dns.log
		else
			if [ -n "`nvram get wan_get_dns | sed 's/ .*//'`" ]; then
				CHINADNS=`nvram get wan_get_dns | sed 's/ .*//'`
				sed -i "s/^ARGS=\(.*\)$old_dns\(.*\)$/ARGS=\1$CHINADNS\2/" $PREFIX/$CHECK/init.d/S24chinadns
				sed -i "s|^\(server.*\)/[^/]*$|\1/$new_dns|" $PREFIX/$CHECK/dnsmasq.d/accelerated-domains.china.conf
			else
				CHINADNS=`cat /tmp/resolv.dnsmasq | awk '/^nameserver/{print $2}' | sed -n '1p'`
				sed -i "s/^ARGS=\(.*\)$old_dns\(.*\)$/ARGS=\1$CHINADNS\2/" $PREFIX/$CHECK/init.d/S24chinadns
				sed -i "s|^\(server.*\)/[^/]*$|\1/$new_dns|" $PREFIX/$CHECK/dnsmasq.d/accelerated-domains.china.conf
			fi
		fi
	}

	sleep 2
	if [ -f "$PREFIX/shadowsocks/chnroutes.lock" ]; then
		$PREFIX/shadowsocks/shadowsocks -u
	else
		:
	fi

	if [ "$adbyby_filter" == "1" ]; then
		touch /var/log/adbyby.lock
		touch /opt/var/log/adbyby.lock
	else
		if [ "$adbyby_filter_global" == "1" ]; then
		touch /var/log/adbyby_global.lock
		touch /opt/var/log/adbyby.lock
		fi
	fi

	[ "$check_dns" == "1" ] && check_dns

	PROCESS=$(ps | grep "ss-redir" | grep -v "grep")
	if [ -z "$PROCESS" ]; then
		/opt/etc/init.d/S22shadowsocks start && touch /var/log/shadowsocks.lock
#		/opt/etc/init.d/S23ss-tunnel start && touch /var/log/ss-tunnel.lock
#		/opt/etc/init.d/S26pdnsd start && touch /var/log/pdnsd.lock
#		/opt/etc/init.d/S24chinadns start && touch /var/log/chinadns.lock
#		/opt/etc/init.d/S27pcap_dnsproxy start && touch /var/log/pcap_dnsproxy.lock
#		/opt/etc/init.d/S29dnscrypt-proxy start && touch /var/log/dnscrypt-proxy.lock
		exit 0
	else
		for i in `cat /var/log/server.txt`;do
        		for j in `cat $PREFIX/opt/var/log/server.txt`;do
                		if [ $i == $j ]; then
					echo "$(date): OK" >> /var/log/account_switching.log
				else
					/opt/etc/init.d/S22shadowsocks restart
#					/opt/etc/init.d/S23ss-tunnel restart
					$PREFIX/shadowsocks/shadowsocks -f
					sleep 2
					$PREFIX/shadowsocks/shadowsocks -r
				fi
			done
		done
	fi
	;;

-r | --rules)
	nvram get wan_ipaddr > /var/log/wan_ipaddr.log
	sed -n 's/.*ver": *"\(.*\)".*/\1/p' $CHECK/shadowsocks.json  > $PREFIX/opt/var/log/server.txt
	/opt/etc/init.d/S99ss-rules start
	echo -e -n "$ansi_white Loading iptables rules... "
	sleep 1
	echo -e "            $ansi_green done. $ansi_std"
	;;

-ad | --adbyby)
	usage() {
		cat <<-EOF
		Usage: adbyby [options]

		Valid options are:

		    -l <lan_ip_list>         network control device filters
		    -c <clear_lan_ip>        clean up ip
		    -A <adbyby_dns_list>
		    -f                       flush rules of adbyby
	EOF
		exit $1
	}

	ipset_f() {
		$IPT -D PREROUTING -p tcp --dport 80 \
			-m set ! --match-set adbyby_lan_ac src \
			-j ADBYBY_AC 2>/dev/null
		$IPT -D PREROUTING -p tcp --dport 80 \
			-m set --match-set ADBYBY dst \
			-j REDIRECT --to 8118 2>/dev/null
		$IPT -F ADBYBY_AC 2>/dev/null
		$IPT -F ADBYBY_FW 2>/dev/null
		$IPT -X ADBYBY_AC 2>/dev/null
		$IPT -X ADBYBY_FW 2>/dev/null
		ipset -X adbyby_lan_ac 2>/dev/null
		ipset -X adbyby_wan_ac 2>/dev/null
		ipset -X ADBYBY 2>/dev/null
		return 0
	}

	adbyby_dns() {
		if [ "$ADBYBY_LIST" = 1 ]; then
			ipset -N ADBYBY hash:ip
			ipset -A ADBYBY 100.100.100.100
			$IPT -A PREROUTING -p tcp --dport 80 \
				-m set --match-set ADBYBY dst \
				-j REDIRECT --to 8118
		fi
		[ ! -f $CHECK/dnsmasq.d/adbyby.dns ] && wget -t0 -O- $adbyby_dns > $CHECK/dnsmasq.d/adbyby.dns
		return 0
	}

	ipset_r() {
		ipset -! -R <<-EOF || return 1
			create adbyby_wan_ac hash:net
			$(adbyby_iplist | sed -e "s/^/add adbyby_wan_ac /")
	EOF
		$IPT -N ADBYBY_AC
		$IPT -A ADBYBY_AC -m set --match-set adbyby_wan_ac dst -j RETURN
		return $?
	}

	fw_rules() {
		ipset -! -R <<-EOF || return 1
			create adbyby_lan_ac hash:net
			$(sed -e "s/^/add adbyby_lan_ac /" ${LAN_CONTROL:=/dev/null} 2>/dev/null)
	EOF
		$IPT -N ADBYBY_FW && \
		$IPT -A ADBYBY_AC -j ADBYBY_FW && \
		$IPT -A ADBYBY_FW -p tcp --dport 80 \
			-j REDIRECT --to-ports 8118 && \
		$IPT -A PREROUTING -p tcp --dport 80 \
			-m set ! --match-set adbyby_lan_ac src -j ADBYBY_AC
		return $?
	}

	adbyby_iplist() {
		cat <<-EOF | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}"
			0.0.0.0/8
			10.0.0.0/8
			100.64.0.0/10
			127.0.0.0/8
			169.254.0.0/16
			172.16.0.0/12
			192.0.0.0/24
			192.0.2.0/24
			192.88.99.0/24
			192.168.0.0/16
			198.18.0.0/15
			198.51.100.0/24
			203.0.113.0/24
			224.0.0.0/4
			240.0.0.0/4
			255.255.255.255
	EOF
	}

	start_adbyby() {
		[ -f "/opt/var/log/adbyby.lock" ] && {
			/opt/etc/init.d/S30adbyby start && touch /opt/var/log/adbyby.lock
		}
		return 0
	}

	while getopts ":l:cASf" arg; do
		case "$arg" in
			l)
				LAN_CONTROL=$OPTARG
				;;
			c)
				ipset -F adbyby_lan_ac
				exit 0
				;;
			A)
				ADBYBY_LIST=1
				;;
			S)
				touch /opt/var/log/adbyby.lock
				;;
			f)
				ipset_f && /opt/etc/init.d/S30adbyby stop
				rm -rf /opt/var/log/adbyby.lock
				exit 0
				;;
		esac
	done

	if [ "$ADBYBY_LIST" = 1 ]; then
		:
	else
		if [ -z "$LAN_CONTROL" ]; then
			usage 2
		fi
	fi

	if [ -n "$LAN_CONTROL" ]; then
		ipset_f && ipset_r && fw_rules && start_adbyby
		[ "$?" = 0 ] || logger "adbyby failed!"
		exit $?
	else
		ipset_f && adbyby_dns && start_adbyby
		[ "$?" = 0 ] || logger "adbyby failed!"
		exit $?
	fi
	;;

-g | --global)
	case ${2} in
		start)
			echo -e "$ansi_red **WARNING** USE AT YOUR OWN RISK! You want to ${2} global?(y/N) $ansi_std"
			read choice
			if [ "${choice}" == "y" ]; then
				touch $CHECK/global.list
				sed -i 's/\$ignore_list/$global_list/' /opt/bin/ss-watchdog
				echo -e -n "$ansi_white ${2} Global... "
				sleep 1
				echo -e "            $ansi_green done. $ansi_std"
			else
				: ${warning:?"You do not have any operations."}
			fi
		;;

		stop)
			echo -e "$ansi_red **WARNING** USE AT YOUR OWN RISK! You want to ${2} global?(y/N) $ansi_std"
			read choice
			if [ "${choice}" == "y" ]; then
				touch $CHECK/global.list
				sed -i 's/\$global_list/$ignore_list/' /opt/bin/ss-watchdog
				echo -e -n "$ansi_white ${2} Global... "
				sleep 1
				echo -e "            $ansi_green done. $ansi_std"
			else
				: ${warning:?"You do not have any operations."}
			fi
		;;
		esac

	$PREFIX/shadowsocks/shadowsocks -f
	$PREFIX/shadowsocks/shadowsocks -r
	;;

-f | --flush)
	ss-nat -f
	echo -e -n "$ansi_white Flush_iptables... "
	sleep 1
	echo -e "            $ansi_green done. $ansi_std"
	;;

-u | --update)
	directory=$(cd $CHECK && ls | grep "dnsmasq.d" | grep -v "grep")
	if [ -z "$directory" ]; then
		cd $CHECK && mkdir dnsmasq.d
	fi

	if [ -f "$CHECK/ignore.list" ]; then
		rm -f $CHECK/ignore.list
	fi

	wget -t0 -O- $china_routing_list | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > /var/log/ignore_tmp.txt

	IGNORE_TEMP_LIST=/var/log/ignore_tmp.txt
	IGNORE_LIST=$CHECK/ignore.list

	cat > $IGNORE_LIST <<-EOF
	0.0.0.0/8
	10.0.0.0/8
	100.64.0.0/10
	127.0.0.0/8
	169.254.0.0/16
	172.16.0.0/12
	192.0.0.0/24
	192.0.2.0/24
	192.88.99.0/24
	192.168.0.0/16
	198.18.0.0/15
	198.51.100.0/24
	203.0.113.0/24
	224.0.0.0/4
	240.0.0.0/4
	255.255.255.255
	$(cat ${IGNORE_TEMP_LIST:=/dev/null} 2>/dev/null)
	EOF

	if [ -f "/var/log/pcap_dnsproxy.lock" ]; then
		rm -f $CHECK/pcap-dnsproxy/Routing.txt $CHECK/pcap-dnsproxy/WhiteList.txt

		# Update Local Hosts
		cd /tmp;curl --insecure -O $china_domain_list;cd /tmp/root
		echo -e '[Local Hosts]' >> /tmp/WhiteList.txt
		echo -e '## China mainland domains' >> /tmp/WhiteList.txt
		echo -e '## Get the latest database: https://github.com/xinhugo/Free-List/blob/master/WhiteList.txt' >> /tmp/WhiteList.txt
		echo -e '## Report an issue: https://github.com/xinhugo/Free-List/issues' >> /tmp/WhiteList.txt
		echo -e "## Last update: $DATE\n" >> /tmp/WhiteList.txt
		sed 's|/114.114.114.114$||' /tmp/accelerated-domains.china.conf > /tmp/WhiteList_tmp.txt
		sed -i 's|\(\.\)|\\\1|g' /tmp/WhiteList_tmp.txt
		sed -i 's|server=/|.*\\\b|' /tmp/WhiteList_tmp.txt
		sed -i 's|b\(cn\)$|\.\1|' /tmp/WhiteList_tmp.txt
		cat /tmp/WhiteList_tmp.txt >> /tmp/WhiteList.txt

		cd /tmp;curl --insecure -O $china_google_list;cd /tmp/root
		sed 's|/114.114.114.114$||' /tmp/google.china.conf > /tmp/WhiteList_tmp.txt
		sed -i 's|\(\.\)|\\\1|g' /tmp/WhiteList_tmp.txt
		sed -i 's|server=/|.*\\\b|' /tmp/WhiteList_tmp.txt
		cat /tmp/WhiteList_tmp.txt >> /tmp/WhiteList.txt
		echo -e -n "$ansi_white Updating Local Hosts... "
		sleep 1
		echo -e "            $ansi_green done. $ansi_std"

		cp /tmp/WhiteList.txt $CHECK/pcap-dnsproxy
		rm -f /tmp/WhiteList_tmp.txt /tmp/WhiteList.txt /tmp/accelerated-domains.china.conf /tmp/google.china.conf

		# Update Local Routing
		curl --insecure $china_routing_list | grep ipv4 | grep CN | awk -F\| '{printf("%s/%d\n", $4, 32-log($5)/log(2))}' > /tmp/Routing_IPv4.txt
		echo -e '[Local Routing]' >> /tmp/Routing_IPv4_tmp.txt
		echo -e '## China mainland routing blocks' >> /tmp/Routing_IPv4_tmp.txt
		echo -e "## Last update: $DATE\n\n" >> /tmp/Routing_IPv4_tmp.txt
		echo -e '## IPv4' >> /tmp/Routing_IPv4_tmp.txt
		echo -e '## Get the latest database from APNIC -> https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' >> /tmp/Routing_IPv4_tmp.txt
		cat /tmp/Routing_IPv4.txt >> /tmp/Routing_IPv4_tmp.txt

		curl --insecure $china_routing_list | grep ipv6 | grep CN | awk -F\| '{printf("%s/%d\n", $4, $5)}' > /tmp/Routing_IPv6.txt
		echo -e '## IPv6' >> /tmp/Routing_IPv6_tmp.txt
		echo -e '## Get the latest database from APNIC -> https://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' >> /tmp/Routing_IPv6_tmp.txt
		cat /tmp/Routing_IPv6.txt >> /tmp/Routing_IPv6_tmp.txt

		cat /tmp/Routing_IPv6_tmp.txt >> /tmp/Routing_IPv4_tmp.txt
		touch /tmp/Routing.txt
		cat /tmp/Routing_IPv4_tmp.txt >> /tmp/Routing.txt
		echo -e -n "$ansi_white Updating Local Routing... "
		sleep 1
		echo -e "            $ansi_green done. $ansi_std"

		cp /tmp/Routing.txt $CHECK/pcap-dnsproxy
		rm -f /tmp/Routing_IPv4.txt /tmp/Routing_IPv4_tmp.txt /tmp/Routing_IPv6.txt /tmp/Routing_IPv6_tmp.txt /tmp/Routing.txt
	else
		wget -t0 -O- $china_routing_list | awk -F\| '/CN\|ipv4/ { printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > $CHECK/chnroute.txt
		cd $CHECK/dnsmasq.d;curl -s --insecure -O $china_domain_list;cd /tmp/root
		DNS=`cat /tmp/resolv.dnsmasq | awk '/^nameserver/{print $2}' | sed -n '1p'`
		sed -i "s|^\(server.*\)/[^/]*$|\1/$DNS|" $CHECK/dnsmasq.d/accelerated-domains.china.conf
	fi

	rm -f $PREFIX/shadowsocks/dns.list
	rm -f $IGNORE_TEMP_LIST

	if [ -f "$PREFIX/shadowsocks/update.lock" ]; then
		echo '['$DATE'] Has loaded China route table.' > /var/log/chnroutes.log
	else
		if [ -f "/var/log/pcap_dnsproxy.lock" ]; then
			/opt/etc/init.d/S27pcap-dnsproxy restart
			$PREFIX/shadowsocks/shadowsocks -f
			sleep 1
			$PREFIX/shadowsocks/shadowsocks -r
		else
			/opt/etc/init.d/S24chinadns restart
			$PREFIX/shadowsocks/shadowsocks -f
			sleep 1
			$PREFIX/shadowsocks/shadowsocks -r
		fi
	fi
	stopservice dnsmasq && \
		startservice dnsmasq
	echo -e -n "$ansi_white Updating chnroutes... "
	sleep 1
	echo -e "            $ansi_green done. $ansi_std"
	;;

-ug | --update_gfwlist)
	echo -e -n "$ansi_white Updating gfwlist... "
	directory=$(cd $CHECK && ls | grep "dnsmasq.d" | grep -v "grep")
	if [ -z "$directory" ]; then
		cd $CHECK && mkdir dnsmasq.d
	fi

	DNS=127.0.0.1#1054

	cd $CHECK/dnsmasq.d;curl --insecure -O $ops_list;cd /tmp/root

	sed -i "s|^\(server.*\)/[^/]*$|\1/$DNS|" $CHECK/dnsmasq.d/opslist.conf
	sed -i "s|^\(ipset.*\)/[^/]*$|\1/gfw_black_list|" $CHECK/dnsmasq.d/opslist.conf
	sleep 1
	echo -e "            $ansi_green done. $ansi_std"
	stopservice dnsmasq && \
		startservice dnsmasq
	;;

-c | --check)
	SHADOWSOCKS=$(ps | grep "ss-redir" | grep -v "grep")
	if [ -f "/var/log/shadowsocks.lock" ]; then
		if [ -z "$SHADOWSOCKS" ]; then
        		echo '['$DATE'] Shadowsoks abnormal operation, restarting shadowsocks.' >> /var/log/shadowsocks_watchdog.log 2>&1
			/opt/etc/init.d/S22shadowsocks start
		else
      			echo '['$DATE'] No problem, the normal operation of shadowsoks.' >> /var/log/shadowsocks_watchdog.log 2>&1
		fi
	fi

	if [ -f "/var/log/chnroutes.lock" ]; then
		if [ "`$IPT -t nat -nvL | grep "SS_SPEC_WAN_AC" | wc -l`" -eq 4 ]; then
			:
		else
			/opt/bin/shadowsocks -r
		fi
	else
		if [ "`$IPT -nvL | grep "gfw_black_list" | wc -l`" -eq 2 ]; then
			:
		else
			/opt/bin/shadowsocks -r
		fi
	fi

	dnscrypt=$(ps | grep "dnscrypt-proxy" | grep -v "grep")
	if [ -f "/var/log/dnscrypt-proxy.lock" ]; then
		if [ -z "$dnscrypt" ]; then
			echo '['$DATE'] dnscrypt-proxy abnormal operation, restarting dnscrypt-proxy.' >> /var/log/dnscrypt-proxy_watchdog.log 2>&1
#			/opt/etc/init.d/S29dnscrypt-proxy start
		else
			echo '['$DATE'] No problem, the normal operation of dnscrypt-proxy.' >> /var/log/dnscrypt-proxy_watchdog.log 2>&1
		fi
	fi

	Pcap_DNSProxy=$(ps | grep "Pcap_DNSProxy" | grep -v "grep")
	if [ -f "/var/log/pcap_dnsproxy.lock" ]; then
		if [ -z "$Pcap_DNSProxy" ]; then
			echo '['$DATE'] Pcap_DNSProxy abnormal operation, restarting Pcap_DNSProxy.' >> /var/log/Pcap_DNSProxy_watchdog.log 2>&1
#			/opt/etc/init.d/S27pcap_dnsproxy start
		else
			echo '['$DATE'] No problem, the normal operation of Pcap_DNSProxy.' >> /var/log/Pcap_DNSProxy_watchdog.log 2>&1
		fi
	fi

	PDNSD=$(ps | grep "pdnsd" | grep -v "grep")
	if [ -f "/var/log/pdnsd.lock" ]; then
		if [ -z "$PDNSD" ]; then
			echo '['$DATE'] Pdnsd abnormal operation, restarting pdnsd.' >> /var/log/pdnsd_watchdog.log 2>&1
#			/opt/etc/init.d/S26pdnsd start
		else
			echo '['$DATE'] No problem, the normal operation of pdnsd.' >> /var/log/pdnsd_watchdog.log 2>&1
		fi
	fi

	judge=$(cd $CHECK && ls | grep "ignore.list" | grep -v "grep")
	if [ -z "$judge" ]; then
		exit 0
	else
		CHINADNS=$(ps | grep "chinadns" | grep -v "grep")
		if [ -f "/var/log/chinadns.lock" ]; then
			if [ -z "$CHINADNS" ]; then
				echo '['$DATE'] ChinaDNS is restarting.' >> /var/log/chinadns_watchdog.log 2>&1
#				/opt/etc/init.d/S24chinadns start
			else
				echo '['$DATE'] ChinaDNS no problem.' >> /var/log/chinadns_watchdog.log 2>&1
			fi
		fi
	fi
	;;

-sw | --ss_switch)
	yes_or_no() {
		read -p "$1 ([y]es or [n]o): "
		case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
			y|yes) echo "yes" ;;
			*)     echo "no" ;;
		esac
	}

	echo -e "$ansi_white Do you want to edit json file?(y/N)$ansi_std"
	if [ "yes" == $(yes_or_no) ]; then
		echo -e $INFO Creating JSON file...
		rm -f $CHECK/shadowsocks.json

		echo "============================================"
		echo "Please input your shadowsocks account imformation:"
		read -p "(Your Server IP):" IP
		read -p "(Your Server Port):" port
		read -p "(Your Local Port):" PORT
		read -p "(Your Password):" password
		read -p "(Your Encryption Method):" method
		echo "============================================"
		echo "Please confirm your shadowsocks imformation:"
		echo -e "Your Server IP: \033[41;37m ${IP} \033[0m"
		echo -e "Your Server Port: \033[41;37m ${port} \033[0m"
		echo -e "Your Server Port: \033[41;37m ${PORT} \033[0m"
		echo -e "Your Password: \033[41;37m ${password} \033[0m"
		echo -e "Your Encryption Method: \033[41;37m ${method} \033[0m"
		echo "============================================"

		ping -q -w1 ${IP} | grep "PING" | sed -e "s;).*;;" -e "s;.*(;;" > /opt/var/log/resolvip_tmp.txt
		ping_ip() {
			ping -q -w1 ${IP} &> /dev/null
			return $?
		}

		ping_ip
		if [ ! "$?" = 0 ]; then
			echo -e "$WARNING You input an incorrect IP, please re-enter your: $ansi_white \nshadowsocks ss_switch"$NORM
			exit 0
		fi

		server_ip=/opt/var/log/resolvip_tmp.txt

		get_server_ip() {
			cat <<-EOF | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}"
				$(cat ${server_ip=:/dev/null} 2>/dev/null)
		EOF
		}
		echo $(get_server_ip) > /opt/var/log/resolvip.txt
		sed -i '/^$/d' /opt/var/log/resolvip.txt
		if [ -s "/opt/var/log/resolvip.txt" ]; then
			echo -e -n $ss_switch
			RIP=`sed -n '1p' /opt/var/log/resolvip.txt`
			cat > $CHECK/shadowsocks.json <<-end
{
    "server":"$RIP",
    "server_port":${port},
    "local_address":"0.0.0.0",
    "local_port":${PORT},
    "password":"${password}",
    "timeout":60,
    "method":"${method}"
}
			end
			sed -i '11d' $CHECK/shadowsocks.json
			sleep 1 
			echo -e "$ansi_green PASS. $ansi_std"
		else
			echo -e -n $ss_switch
			sleep 1 
			echo -e "$ansi_red ERROR. $ansi_std"
			echo -e "$WARNING Can not write the configuration information, please re-enter your: $ansi_white \nshadowsocks ss_switch"$NORM
			exit 0
		fi
	else
		echo -e $INFO Creating server file...
		echo "============================================"
		echo "Please input your shadowsocks account imformation:"
		read -p "(Your Server IP):" IP
		echo "============================================"
		echo "Please confirm your shadowsocks imformation:"
		echo -e "Your Server IP: \033[41;37m ${IP} \033[0m"
		echo "============================================"

		ping -q -w1 ${IP} | grep "PING" | sed -e "s;).*;;" -e "s;.*(;;" > /opt/var/log/resolvip_tmp.txt
		ping_ip() {
			ping -q -w1 ${IP} &> /dev/null
			return $?
		}

		ping_ip
		if [ ! "$?" = 0 ]; then
			echo -e "$WARNING You input an incorrect IP, please re-enter your: $ansi_white \nshadowsocks ss_switch"$NORM
			exit 0
		fi

		server_ip=/opt/var/log/resolvip_tmp.txt

		get_server_ip() {
			cat <<-EOF | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}"
				$(cat ${server_ip=:/dev/null} 2>/dev/null)
		EOF
		}
		echo $(get_server_ip) > /opt/var/log/resolvip.txt
		sed -i '/^$/d' /opt/var/log/resolvip.txt
		if [ -s "/opt/var/log/resolvip.txt" ]; then
			echo -e -n $ss_switch
			RIP=`sed -n '1p' /opt/var/log/resolvip.txt`
			sed -i 's/\("server":"\).*/\1'"$RIP"'",/g' $CHECK/shadowsocks.json
			sleep 1
			echo -e "$ansi_green PASS. $ansi_std"
		else
			echo -e -n $ss_switch
			sleep 1
			echo -e "$ansi_red ERROR. $ansi_std"
			echo -e "$WARNING Can not write IP, please re-enter your: $ansi_white \nshadowsocks ss_switch"$NORM
			exit 0
		fi
	fi

	$PREFIX/shadowsocks/shadowsocks -S
	stopservice dnsmasq && \
		startservice dnsmasq
	;;

-sa | --services_action)
	case ${2} in
		stop)
			echo -e "$ansi_red **WARNING** USE AT YOUR OWN RISK! You want to ${2} all service under /opt/etc/init.d?(y/N) $ansi_std"
			read choice
			if [ "${choice}" == "y" ]; then
				/opt/etc/init.d/rc.unslung ${2}
				if [ "${2}" == "stop" ]; then
					cp $CHECK/dnsmasq.conf $CHECK/dnsmasq.conf.bak
					cp /tmp/etc/dnsmasq.conf $CHECK/dnsmasq.conf
					$PREFIX/shadowsocks/shadowsocks -f
					killall dnsmasq && \
						/opt/etc/init.d/S56dnsmasq restart
				fi
			else
				: ${warning:?"You do not have any operations."}
			fi
		;;

		start)
			echo -e "$ansi_red **WARNING** USE AT YOUR OWN RISK! You want to ${2} all service under /opt/etc/init.d?(y/N) $ansi_std"
			read choice
			if [ "${choice}" == "y" ]; then
				if [ "${2}" == "start" ]; then
					cp $CHECK/dnsmasq.conf.bak $CHECK/dnsmasq.conf
					$PREFIX/shadowsocks/shadowsocks -f && \
					$PREFIX/shadowsocks/shadowsocks -S && \
					$PREFIX/shadowsocks/shadowsocks -r
					stopservice dnsmasq && \
						startservice dnsmasq
				fi
			else
				: ${warning:?"You do not have any operations."}
			fi
		;;

	*)
		echo -e "$ansi_white usage: [stop|start] $ansi_std"
	esac
	;;

-us | --update_scr)
	yes_or_no() {
    		read -p "$1 ([y]es or [n]o): "
    		case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
        		y|yes) echo "yes" ;;
        		*)     echo "no" ;;
    		esac
	}

	SCRIPT_INSTALL=$(cd ${SCRIPT_DIR} && cd .. && pwd)

	if [ ! "$SCRIPT_DIR" == "$PREFIX" ]; then
		sed -i 's;PREFIX='"$PREFIX"';PREFIX='"$SCRIPT_INSTALL"';' $SCRIPT_DIR/shadowsocks
	fi

	echo -e $INFO Choose $BOLD CHNROUTES or GFWLIST $NORM? "\033[4m yes \033[0m"  or "\033[4m no \033[0m"
	if [ "yes" == $(yes_or_no "CHNROUTES?") ]; then
		if [ "yes" == $(yes_or_no "ss-redir?") ]; then
			echo -e $INFO Is updating the script......
			if [ -f "/var/log/pcap_dnsproxy.lock" ]; then
				sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S27pcap-dnsproxy (start))/\1/' $SCRIPT_INSTALL/shadowsocks/shadowsocks -i $SCRIPT_INSTALL/shadowsocks/shadowsocks
			else
				sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S24chinadns (start))/\1/' $SCRIPT_INSTALL/shadowsocks/shadowsocks -i $SCRIPT_INSTALL/shadowsocks/shadowsocks
				[ -f "/var/log/pdnsd.lock" ] && sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S26pdnsd (start))/\1/' $SCRIPT_INSTALL/shadowsocks/shadowsocks -i $SCRIPT_INSTALL/shadowsocks/shadowsocks
				[ -f "/var/log/dnscrypt-proxy.lock" ] && sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S29dnscrypt-proxy (start))/\1/' $SCRIPT_INSTALL/shadowsocks/shadowsocks -i $SCRIPT_INSTALL/shadowsocks/shadowsocks
			fi
		else
			echo -e $INFO Is updating the script......
			sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S23ss-tunnel (start|restart))/\1/' $SCRIPT_INSTALL/shadowsocks/shadowsocks -i $SCRIPT_INSTALL/shadowsocks/shadowsocks
			sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S24chinadns (start))/\1/' $SCRIPT_INSTALL/shadowsocks/shadowsocks -i $SCRIPT_INSTALL/shadowsocks/shadowsocks
		fi
	else
		echo -e $INFO Is updating the script......
		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S26pdnsd (start))/\1/' $SCRIPT_INSTALL/shadowsocks/shadowsocks -i $SCRIPT_INSTALL/shadowsocks/shadowsocks
	fi

	echo -e -n $update_scr
	sleep 1
	echo -e "$ansi_green PASS. $ansi_std"
	;;

-b | --backup)
	echo -e "$ansi_white You want to backup entware?(y/N)$ansi_std"
	read choice
	if [ "${choice}" == "y" ]; then
		tar -czf /tmp/entware_backup.tar.gz -C $PREFIX opt
		[ ! -d "$PREFIX/shadowsocks/entware_backup" ] && mkdir -p $PREFIX/shadowsocks/entware_backup
		cp /tmp/entware_backup.tar.gz $PREFIX/shadowsocks/entware_backup/
	fi

	echo -e -n $backup
	sleep 1
	echo -e "$ansi_green PASS. $ansi_std"
	;;

-e | --email)
	curl -s --connect-timeout 1 www.google.com &> /dev/null

	if [ "$?" == "0" ]; then
		echo -e "From: $FROM\nContent-Type: text/plain;\nSubject: $TITLE\n\n$CONTENT\nAt: `date -R`" > /tmp/mail.txt
		cat /tmp/mail.txt | sendmail -v -Ssmtp.163.com -f$FROM -au$username -ap$password $TO &> /dev/null
	fi
	;;

-h | --help)
	shadowsocks
	;;

*)
	echo -e "$ansi_green # ------------------------------------------------------------------- $ansi_std"
	echo -e "$ansi_green # Copyright (C) 2016 Jason Lin <wojiaolinmu008@gmail.com> $ansi_std"
	echo -e "$ansi_green # Last edited: 2016.8.2 $ansi_std"
	echo -e "$ansi_green # Version: V1.5-stable (ARM version) $ansi_std"
	echo -e "$ansi_green # Explain: This script can be used only for DD-WRT ARM firmware. $ansi_std"
	echo -e "$ansi_green # Description: This is a science on ShadowSocks Internet automatic $ansi_std"
	echo -e "$ansi_green # configuration script in DD-WRT under$ansi_std. "
	echo -e "$ansi_green # This is free software, licensed under the GNU General Public License v3. $ansi_std"
	echo -e "$ansi_green # See /LICENSE for more information. $ansi_std"
	echo -e "$ansi_green # ------------------------------------------------------------------- $ansi_std"
	echo -e "$ansi_white ===================================================================== $ansi_std"
	echo -e "$ansi_blue WIKI: $ansi_std"
	echo -e "$ansi_white   [-su/--set_up] Set ShadowSocks and ChinaDNS $ansi_std"
	echo -e "$ansi_white   [-m/--modules] Loading module $ansi_std"
	echo -e "$ansi_white   [-S/--START] Running ShadowSocks and ChinaDNS $ansi_std"
	echo -e "$ansi_white   [-r/--rules] Application Firewall Policy $ansi_std"
	echo -e "$ansi_white   [-ad/--adbyby] Ad Filter $ansi_std"
	echo -e "$ansi_white   [-g/--global] Global Proxy $ansi_std"
	echo -e "$ansi_white   [-f/--flush] Clear firewall policy $ansi_std"
	echo -e "$ansi_white   [-u/--update] Update chnroutes Routing Host $ansi_std"
	echo -e "$ansi_white   [-ug/--update_gfwlist] Update GFWLIST domain $ansi_std"
	echo -e "$ansi_white   [-c/--check] Guardian ss-redir* $ansi_std"
	echo -e "$ansi_white   [-sw/--ss_switch] Account switching $ansi_std"
	echo -e "$ansi_white   [-sa/--services_action] Change all state services $ansi_std"
	echo -e "$ansi_white   [-us/--update_scr] Update script $ansi_std"
	echo -e "$ansi_white   [-b/--backup] Backup entware $ansi_std"
	echo -e "$ansi_white   [-e/--email] Send shadowsocks running information $ansi_std"
	echo -e "$ansi_white   [-h/--help] Script help $ansi_std"
	echo -e "$ansi_white ===================================================================== $ansi_std"
	exit
	;;
esac
