#!/bin/sh
#
# Copyright (C) 2015-2016 DD-WRT shadowsocks  
# Copyright (C) 2015-2016 Jason Lin <wojiaolinmu008@gmail.com>
# --------------------------------------------------------------------------------------------------------
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
# --------------------------------------------------------------------------------------------------------
#

# Debug 
#set -x
# SMTP server (EP:"smtp.gmail.com")
SMTP="smtp.163.com"
# Send E-mail Username
username=""
# Send E-mail password
password=""
# Sender E-mail
FROM=""
# E-mail Subject
TITLE="ShadowSocks"
# Content of E-mail
CONTENT="Your tools running over the wall!"
# Target E-mail address
TO=""

# XIAOMI Fan Mode
#xiaomi_fan=0

# ADM ad filter
#adm_filter=0

READ="\033[31;1m"
BOLD="\033[42;1m"	
NORM="\033[0m"
ansi_red="\033[1;31m";
ansi_white="\033[1;37m";
ansi_green="\033[1;32m";
ansi_yellow="\033[1;33m";
ansi_blue="\033[1;34m";
ansi_bell="\007";
ansi_blink="\033[5m";
ansi_std="\033[m";
ansi_rev="\033[7m";
ansi_ul="\033[4m";
INFO="$BOLD INFO: $NORM"
WARNING="$READ WARNING: $NORM"
MOUNT="$ansi_white MOUNT: "
DEPENDENCE="$ansi_white DEPENDENCE: "
PLATFORM="$ansi_white PLATFORM: "
PACKAGES="$ansi_white PACKAGES: "
SHADOWSOCKS="$ansi_white SHADOWSOCKS: "
START_SCRIPT="$ansi_white START_SCRIPT: "
ShadowSocks_Account="$ansi_white ShadowSocks_Account: "
DNSMASQ="$ansi_white DNSMASQ: "
ZONEINFO_ASIA="$ansi_white ZONEINFO_ASIA: "
mult_switch="$ansi_white mult_switch: "
ss_switch="$ansi_white ss_switch: "
update_scr="$ansi_white update_scr: "
rebuild_scr="$ansi_white rebuild_scr: "

# You can mount the partition path editing (EP:"/jffs" or "/tmp/mnt/sda1" )
PREFIX=/jffs
SCRIPT_DIR=$(dirname ${0})
SCRIPT_DIR=$(cd ${SCRIPT_DIR} && pwd)

# Time
DATE=$(date "+%Y-%m-%d %H:%M:%S")

# Schduler
CHECK=/opt/etc

# Link
gfw_block_list="https://raw.githubusercontent.com/koolshare/koolshare.github.io/master/maintain_files/gfwlist.conf"
china_routing_list="http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest"
china_domain_list="https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf"
china_google_list="https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf"

case ${1} in

"set_up" )
	DECIVE=$(cat /proc/cpuinfo | grep "ARMv7" | grep -v "grep")
	if [ -z "$DECIVE" ]; then
		echo -e -n $PLATFORM
		sleep 1
		echo -e "$ansi_red ERROR. $ansi_std"
		echo -e $WARNING $BOLD This script is not suitable for the platform,can not continue.$NORM 
		exit 0
	else
		if [ ! -d "$PREFIX/shadowsocks" ]; then
			echo -e $INFO "Creating in..."
			cd $PREFIX;mkdir -p opt;mkdir -p shadowsocks;cd /;cd /tmp/root
			cp $SCRIPT_DIR/shadowsocks $PREFIX/shadowsocks
			mount -o bind $PREFIX/opt /opt
			cd /opt && wget -O - http://pkg.entware.net/binaries/armv7/installer/entware_install.sh | sh
			tar -czf /tmp/opt_backup_old.tar.gz -C $PREFIX opt			
			if [ -e $SCRIPT_DIR/china* -a -e $SCRIPT_DIR/cron* -a -e $SCRIPT_DIR/dif* -a -e $SCRIPT_DIR/pcap_dns* -a -e $SCRIPT_DIR/pdns* -a -e $SCRIPT_DIR/resol* -a -e $SCRIPT_DIR/shadowsocks-libe* -a -e $SCRIPT_DIR/dnscryp* -a -e $SCRIPT_DIR/bash* -a -e $SCRIPT_DIR/dnsma* ]; then
				cd $SCRIPT_DIR && opkg install --force-checksum china* pdnsd* pcap* reso* shadow* diff* dnscr* dnsma* cron* bash*
				echo -e "$ansi_green SHADOWSOCKS script installed successfully! $ansi_std"
				sleep 5
				ln -s $PREFIX/shadowsocks/shadowsocks /opt/bin
				tar -czf /tmp/opt_backup_new.tar.gz -C $PREFIX opt
				mkdir -p $PREFIX/shadowsocks/opt_backup
				cp /tmp/opt_backup_new.tar.gz $PREFIX/shadowsocks/opt_backup/ && cp /tmp/opt_backup_old.tar.gz $PREFIX/shadowsocks/opt_backup/
			else
				echo -e "$ansi_red You do not import the entire IPK! $ansi_std"
				exit 0
			fi	
		else
			echo -e "$ansi_yellow SHADOWSOCKS already installed! $ansi_std"
		fi
		echo -e -n $PLATFORM
		sleep 1 
		echo -e "$ansi_green PASS. $ansi_std"
	fi	

	autorun=/opt/etc/init.d/auto.run
	if [ ! -f "$autorun" ]; then
		echo "#!/bin/sh" >> $autorun
		echo >> $autorun
		echo "if [ -f /tmp/ppp/options.pppoe ]; then" >> $autorun
		echo -e "	mount -o bind $PREFIX/opt /opt" >> $autorun
		echo "	/opt/bin/shadowsocks modules" >> $autorun
		echo "	/opt/bin/shadowsocks run" >> $autorun
		echo "	sleep 1" >> $autorun
		echo "	/opt/bin/shadowsocks rules" >> $autorun		
		echo "fi" >> $autorun
		echo >> $autorun

		sleep 1
		chmod +x $autorun
		ln -s $autorun /opt/bin	
	fi	

	if [ -d "$PREFIX/shadowsocks" ]; then
		echo -e -n $SHADOWSOCKS
		sleep 1
		echo -e "$ansi_green PASS. $ansi_std"
	else
		echo -e -n $SHADOWSOCKS
		sleep 1
		echo -e "$ansi_red ERROR. $ansi_std"
		rm -rf $PREFIX/opt
		echo -e $WARNING $BOLD"Please install the SHADOWSOCKS script."$NORM 
		exit 0		
	fi

	if [ "`ls -A /opt`" = "" ]; then
		echo -e -n $MOUNT
		sleep 1
		echo -e "$ansi_red ERROR. $ansi_std"
		rm -rf $PREFIX/opt
		echo -e $WARNING $BOLD"OPT directory does not mount."$NORM 
		exit 0
	else
		echo -e -n $MOUNT
		sleep 1
		echo -e "$ansi_green PASS. $ansi_std"		
	fi

	BIN=/opt/bin
	SBIN=/opt/sbin
	echo -e "bash \nchinadns \ncrontab \ndiff \ndnscrypt-proxy \nPcap_DNSProxy \npdnsd-ctl \nresolvip \nss-redir \ndnsmasq" > /var/log/find.txt	
	cd $BIN
	if [ ! -f chinadns -o ! -f Pcap_DNSProxy -o ! -f ss-redir -o ! -f resolvip -o ! -f pdnsd-ctl -o ! -f diff -o ! -f dnscrypt-proxy ]; then	
		ls -1 chinadns Pcap_DNSProxy ss-redir resolvip pdnsd-ctl diff dnscrypt-proxy crontab bash > /var/log/find_N.txt
	else
		ls -1 chinadns Pcap_DNSProxy ss-redir resolvip pdnsd-ctl diff dnscrypt-proxy crontab bash > /var/log/find_N.txt
	fi
	cd /
	
	find $SBIN/dnsmasq &> /dev/null;echo $? > /var/log/sbin.txt
	sbin=`sed -n '1p' /var/log/sbin.txt`
	if [ "$sbin" == "0" ]; then
		echo -e -n $DNSMASQ
		sleep 1 
		sed -i '/^$/d' /var/log/find_N.txt
		echo "dnsmasq" >> /var/log/find_N.txt
		echo -e "$ansi_green PASS. $ansi_std"
	else
		echo -e $DNSMASQ
		sleep 1	
		rm -rf $PREFIX/opt
		echo -e $ansi_white"dnsmasq-full"$ansi_std
	fi
	
	find $BIN/chinadns $BIN/Pcap_DNSProxy $BIN/ss-redir $BIN/resolvip $BIN/pdnsd-ctl $BIN/diff $BIN/dnscrypt-proxy $BIN/crontab $SBIN/dnsmasq $BIN/bash &> /dev/null;echo $? > /var/log/diff.txt
	DIFF=`sed -n '1p' /var/log/diff.txt`
	diff -w /var/log/find.txt /var/log/find_N.txt | grep \^\< > /var/log/diff_show.txt
	if [ "$DIFF" == "0" ]; then
		echo -e -n $DEPENDENCE
		sleep 1 
		echo -e "$ansi_green PASS. $ansi_std"
	else
		if [ ! -e $BIN/chinadns -a ! -e $BIN/crontab -a ! -e $BIN/diff -a ! -e $BIN/Pcap_DNSProxy -a ! -e $BIN/pdnsd-ctl -a ! -e $BIN/resolvip -a ! -e $BIN/ss-redir -a ! -e $BIN/dnscrypt-proxy -a ! -e $SBIN/dnsmasq -a ! -e $BIN/bash ]; then
			echo -e $DEPENDENCE
			sleep 1
			echo -e "$ansi_red ERROR. $ansi_std"
			echo -e "$WARNING \n$BOLD Please install the following software:"$NORM
			rm -rf $PREFIX/opt
			echo -e $ansi_white"shadowsocks-libev \nchinadns \npdnsd \npcap-dnsproxy \nresolvip \ndiffutils \ncrontab \ndnscrypt-proxy \ndnsmasq \nbash"$ansi_std
			exit 0
		else	
			echo -e $DEPENDENCE
			sleep 1
			echo -e "$ansi_red ERROR. $ansi_std"
			echo -e "$WARNING \n$BOLD Please install the following software:"$NORM
			rm -rf $PREFIX/opt
			cat /var/log/diff_show.txt
			exit 0
		fi
	fi
	
	if [ -f "$autorun" ]; then
		echo -e -n $START_SCRIPT
		sleep 1
		echo -e "$ansi_green PASS. $ansi_std"
	fi
	
	ask_yes_or_no() {
    		read -p "$1 ([y]es or [n]o): "
    		case $(echo $REPLY | tr '[A-Z]' '[a-z]') in
        		y|yes) echo "yes" ;;
        		*)     echo "no" ;;
    		esac
	}

	echo "============================================"
	echo "Please input your shadowsocks account information:"
	read -p "(Your Server IP):" IP
	read -p "(Your Server Port):" port
	read -p "(Your Local Port):" PORT
	read -p "(Your Password):" password
	read -p "(Your Encryption Method):" method
	echo "============================================"
	echo "Please confirm your shadowsocks information:"
	echo -e "Your Server IP: \033[41;37m ${IP} \033[0m"
	echo -e "Your Server Port: \033[41;37m ${port} \033[0m"
	echo -e "Your Server Port: \033[41;37m ${PORT} \033[0m"
	echo -e "Your Password: \033[41;37m ${password} \033[0m"
	echo -e "Your Encryption Method: \033[41;37m ${method} \033[0m"
	echo "============================================"

	resolvip -t 10 ${IP} > /opt/var/log/resolvip_tmp.txt
	if [ `cat /opt/var/log/resolvip_tmp.txt | cut -d"." -f1` == `resolvip -t 10 192. | cut -d"." -f1` ] &> /dev/null; then
		echo -e "$WARNING You input an incorrect IP, please re-enter your: $ansi_white \nshadowsocks set_up"$NORM
		exit 0					
	fi		
	server_ip=/opt/var/log/resolvip_tmp.txt

	get_server_ip() {
		cat <<-EOF | grep -E "^([0-9]{1,3}\.){3}[0-9]{1,3}"
			$(cat ${server_ip=:/dev/null} 2>/dev/null)	
	EOF
	}
	echo $(get_server_ip) > /opt/var/log/resolvip.txt
	sed -i '/^$/d' /opt/var/log/resolvip.txt
	if [ -s "/opt/var/log/resolvip.txt" ]; then
		RIP=`sed -n '1p' /opt/var/log/resolvip.txt`
		echo -e $INFO Creating shadowsocks config file...
		rm -f $CHECK/shadowsocks.json
		cat > $CHECK/shadowsocks.json <<-end
	{
    "server":"$RIP",
    "server_port":${port},
    "local_address":"0.0.0.0",
    "local_port":${PORT},
    "password":"${password}",
    "timeout":60,
    "method":"${method}"
	}
		end
		sed -i '11d' $CHECK/shadowsocks.json
	else
		echo -e "$WARNING Can not write the configuration information, please re-enter your: $ansi_white \nshadowsocks set_up"$NORM
		exit 0
	fi		
	
	echo -e $INFO Please confirm your shadowsocks and dnsmasq information with "\033[4m yes \033[0m"  or "\033[4m no \033[0m"  to exit
	if [ "no" == $(ask_yes_or_no "Is your config above correct?") ]; then
		echo -e $INFO Re-setting...
  		echo -e $INFO Exiting...
		rm -f $CHECK/shadowsocks.json
  		exit 0 
	fi		

echo -e $INFO "Please select Please choose the following programs:\n\
$BOLD##programs_1##:$NORM (ss-redir+gfwlist+pdnsd)\n\
$BOLD##programs_2##:$NORM (ss-redir+chnroutes+chinadns+pdnsd)\n\
$BOLD##programs_3##:$NORM (ss-redir+chnroutes+chinadns+dnscrypt-proxy)\n\
$BOLD##programs_4##:$NORM (ss-redir+chnroutes+pcap_dnsproxy)\n\
$BOLD##programs_5##:$NORM (ss-tunnel+chnroutes+chinadns)\n\
Your Choice:"
	read programs
	if [ $programs == "1" ];then
		echo -e "$BOLD Set programs_1..." $NORM
		sed -e "s/shadowsocks.json\"/shadowsocks.json\"/" -e "s/PROCS=ss-local/PROCS=ss-redir/" -i  $CHECK/init.d/S22shadowsocks
		sed -n 's/.*ver":"\(.*\)".*/\1/p' $CHECK/shadowsocks.json  > $PREFIX/opt/var/log/server.txt

		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S26pdnsd (start))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks
		
		$PREFIX/shadowsocks/shadowsocks modules
		$PREFIX/shadowsocks/shadowsocks run		
		sleep 1
		$PREFIX/shadowsocks/shadowsocks rules
		$PREFIX/shadowsocks/shadowsocks update_gfwlist

		echo -e $INFO Configuring ntp server...
		cat /etc/resolv.dnsmasq | awk '/^nameserver/{print $2}' > $PREFIX/shadowsocks/dns.list
		DNS=`sed -n '1p' $PREFIX/shadowsocks/dns.list`
		NTP=$PREFIX/shadowsocks/dnsmasq.d/ntp_server.conf
		echo "server=/0.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/1.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/2.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/3.asia.pool.ntp.org/$DNS" >> $NTP
		echo >> $NTP
		rm -f $PREFIX/shadowsocks/dns.list

		nvram set time_zone="Asia/Shanghai"

		echo -e $INFO Configuring dnsmasq_custom...
		nvram set dnsmasq_options="conf-dir=$PREFIX/shadowsocks/dnsmasq.d"
		
		/opt/etc/init.d/S56dnsmasq restart
		
		rm -f $CHECK/pdnsd.conf
		cat > $CHECK/pdnsd.conf <<-end
global {
perm_cache=2048;
cache_dir="/var/pdnsd";
run_as="nobody";
server_port = 1054;
server_ip = 127.0.0.1;  
status_ctl = on;					               
query_method=tcp_only;
min_ttl=6h;       
max_ttl=1w;        
timeout=10;        
}

server {
label= "google";
ip = 208.67.222.222; 
port = 443;   	
root_server = on;    
uptest= none;         
}
		end
		
		$PREFIX/shadowsocks/shadowsocks run
		
		echo -e $INFO Configuring turn startup items and guard the capital...
		echo -e "$PREFIX/opt/etc/init.d/auto.run" > /var/log/scr_c.txt
		SCR=`sed -e '' /var/log/scr_c.txt`
		nvram set rc_startup="$SCR"
		nvram commit
		
		echo -e "echo \"\" > /var/log/shadowsocks_watchdog.log \necho \"\" > /var/log/pdnsd_watchdog.log \necho \"\" > /var/log/iptables_rules.log" > $CHECK/cron.5mins/clear_log.sh
#		echo 'iptables-save | grep -E "gfw_black|ADM_|WANPREROUTING|POSTROUTING|^\*nat" > /var/log/iptables-restore.log' > $CHECK/cron.5mins/iptables_restore.sh
		echo -e "shadowsocks check \nshadowsocks check_rules" > $CHECK/cron.1min/check.sh				

#		shadowsocks temp
#	
		echo -e "$BOLD Set successfully, please reboot the router. $NORM"	
		echo -e "$ansi_red Set successfully, please reboot the router. Found a Bug? Plea se report at https://github.com/houzi-/tomato-shadowsocks/issues. $ansi_std"
		killall shadowsocks > /dev/null
	elif [ $programs == "2" ];then
		echo -e "$BOLD Set programs_2..." $NORM
		sed -e "s/shadowsocks.json\"/shadowsocks.json\"/" -e "s/PROCS=ss-local/PROCS=ss-redir/" -i  $CHECK/init.d/S22shadowsocks
		sed '4c PROCS=chinadns' $CHECK/init.d/S22shadowsocks > $CHECK/init.d/S24cn
		sed '5c ARGS="-p 5353 -c /opt/etc/chnroute.txt -s 114.114.114.114,127.0.0.1:1054"' $CHECK/init.d/S24cn > $CHECK/init.d/S24chinadns

		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S26pdnsd (start))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks
		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S24chinadns (start|restart))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks	
		
		CHINADNS=`nvram get wan_get_dns | sed 's/ /,/'`
		sed -i "s/^ARGS=\(.*\)114.114.114.114\(.*\)$/ARGS=\1$CHINADNS\2/" $CHECK/init.d/S24chinadns
	
		rm -f $CHECK/init.d/S24cn
		chmod +x $CHECK/init.d/S2*

		sleep 1
		echo -e $INFO Creating pdnsd.conf file...
		rm -f $CHECK/pdnsd.conf
		cat > $CHECK/pdnsd.conf <<-end
global {
perm_cache=2048;
cache_dir="/var/pdnsd";
run_as="nobody";
server_port = 1054;
server_ip = 127.0.0.1;  
status_ctl = on;					               
query_method=tcp_only;
min_ttl=6h;       
max_ttl=1w;        
timeout=10;        
}

server {
label= "google";
ip = 208.67.222.222,208.67.220.220;     	
root_server = on;    
uptest= none;         
}
		end

		touch $PREFIX/shadowsocks/update.lock
		touch $PREFIX/shadowsocks/chnroutes.lock
		$PREFIX/shadowsocks/shadowsocks modules	
		sleep 4
		$PREFIX/shadowsocks/shadowsocks run
		sleep 2
		$PREFIX/shadowsocks/shadowsocks rules

		echo -e $INFO Configuring ntp server...
		cat /etc/resolv.dnsmasq | awk '/^nameserver/{print $2}' > $PREFIX/shadowsocks/dns.list
		DNS=`sed -n '1p' $PREFIX/shadowsocks/dns.list`
		NTP=$PREFIX/shadowsocks/dnsmasq.d/ntp_server.conf
		echo "server=/0.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/1.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/2.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/3.asia.pool.ntp.org/$DNS" >> $NTP
		echo >> $NTP
		rm -f $PREFIX/shadowsocks/dns.list

		nvram set time_zone="Asia/Shanghai"		

		echo -e $INFO Configuring dnsmasq_custom...			
		echo -e "no-resolv \nno-poll \nserver=127.0.0.1#5353 \nmin-cache-ttl=6000 \ncache-size=10000 \nconf-dir=$PREFIX/shadowsocks/dnsmasq.d" > /var/log/dnsmasq_custom.txt
		DNS_CUSTOM=`sed -e '' /var/log/dnsmasq_custom.txt`
		nvram set dnsmasq_options="$DNS_CUSTOM"
		
		echo -e $INFO Configuring turn startup items and guard the capital...
		echo -e "$PREFIX/opt/etc/init.d/auto.run" > /var/log/scr_c.txt
		SCR=`sed -e '' /var/log/scr_c.txt`
		nvram set rc_startup="$SCR"
		nvram commit

		echo -e "echo \"\" > /var/log/shadowsocks_watchdog.log \necho \"\" > /var/log/pdnsd_watchdog.log \necho \"\" > /var/log/chinadns_watchdog.log \necho \"\" > /var/log/iptables_rules.log" > $CHECK/cron.5mins/clear_log.sh
		echo 'iptables-save | grep -E "SS_SPEC|ADM_|WANPREROUTING|POSTROUTING|^\*nat" > /var/log/iptables-restore.log' > $CHECK/cron.5mins/iptables_restore.sh
		echo -e "shadowsocks check \nshadowsocks check_rules" > $CHECK/cron.1min/check.sh		

		shadowsocks temp		
		
		rm -f $PREFIX/shadowsocks/update.lock
		rm -f $PREFIX/shadowsocks/chnroutes.lock
		echo -e "$BOLD Set successfully, please reboot the router. $NORM"		
		echo -e "$ansi_red Set successfully, please reboot the router. Found a Bug? Plea se report at https://github.com/houzi-/tomato-shadowsocks/issues. $ansi_std"
		killall shadowsocks > /dev/null
	elif [ $programs == "3" ];then
		echo -e "$BOLD Set programs_3..." $NORM
		sed -e "s/shadowsocks.json\"/shadowsocks.json\"/" -e "s/PROCS=ss-local/PROCS=ss-redir/" -i  $CHECK/init.d/S22shadowsocks
		sed '4c PROCS=chinadns' $CHECK/init.d/S22shadowsocks > $CHECK/init.d/S24cn
		sed '5c ARGS="-p 5353 -c /opt/etc/chnroute.txt -s 114.114.114.114,127.0.0.1:1054,208.67.222.222:443"' $CHECK/init.d/S24cn > $CHECK/init.d/S24chinadns

		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S29dnscrypt-proxy (start))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks
		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S24chinadns (start|restart))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks	

		CHINADNS=`nvram get wan_get_dns | sed 's/ /,/'`
		sed -i "s/^ARGS=\(.*\)114.114.114.114\(.*\)$/ARGS=\1$CHINADNS\2/" $CHECK/init.d/S24chinadns

		rm -f $CHECK/init.d/S24cn
		chmod +x $CHECK/init.d/S2*

		touch $PREFIX/shadowsocks/update.lock
		touch $PREFIX/shadowsocks/chnroutes.lock
		$PREFIX/shadowsocks/shadowsocks modules	
		sleep 4
		$PREFIX/shadowsocks/shadowsocks run
		sleep 2
		$PREFIX/shadowsocks/shadowsocks rules

		echo -e $INFO Configuring ntp server...
		cat /etc/resolv.dnsmasq | awk '/^nameserver/{print $2}' > $PREFIX/shadowsocks/dns.list
		DNS=`sed -n '1p' $PREFIX/shadowsocks/dns.list`
		NTP=$PREFIX/shadowsocks/dnsmasq.d/ntp_server.conf
		echo "server=/0.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/1.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/2.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/3.asia.pool.ntp.org/$DNS" >> $NTP
		echo >> $NTP
		rm -f $PREFIX/shadowsocks/dns.list

		nvram set time_zone="Asia/Shanghai"

		echo -e $INFO Configuring dnsmasq_custom...
		echo -e "no-resolv \nno-poll \nserver=127.0.0.1#5353 \nproxy-dnssec \nmin-cache-ttl=6000 \ncache-size=10000 \nconf-dir=$PREFIX/shadowsocks/dnsmasq.d" > /var/log/dnsmasq_custom.txt
		DNS_CUSTOM=`sed -e '' /var/log/dnsmasq_custom.txt`
		nvram set dnsmasq_options="$DNS_CUSTOM"		

		echo -e $INFO Configuring turn startup items and guard the capital...
		echo -e "$PREFIX/opt/etc/init.d/auto.run" > /var/log/scr_c.txt
		SCR=`sed -e '' /var/log/scr_c.txt`
		nvram set rc_startup="$SCR"
		nvram commit
	
		echo -e "echo \"\" > /var/log/shadowsocks_watchdog.log \necho \"\" > /var/log/dnscrypt-proxy_watchdog.log \necho \"\" > /var/log/chinadns_watchdog.log \necho \"\" > /var/log/iptables_rules.log" > $CHECK/cron.5mins/clear_log.sh
#		echo 'iptables-save | grep -E "SS_SPEC|ADM_|WANPREROUTING|POSTROUTING|^\*nat" > /var/log/iptables-restore.log' > $CHECK/cron.5mins/iptables_restore.sh	
		echo -e "shadowsocks check \nshadowsocks check_rules" > $CHECK/cron.1min/check.sh	

#		shadowsocks temp		
#		
		rm -f $PREFIX/shadowsocks/update.lock
		rm -f $PREFIX/shadowsocks/chnroutes.lock
		echo -e "$BOLD Set successfully, please reboot the router. $NORM"		
		echo -e "$ansi_red Set successfully, please reboot the router. Found a Bug? Plea se report at https://github.com/houzi-/tomato-shadowsocks/issues. $ansi_std"
		killall shadowsocks > /dev/null
	elif [ $programs == "4" ];then
		echo -e "$BOLD Set programs_4..." $NORM
		sed -e "s/shadowsocks.json\"/shadowsocks.json\"/" -e "s/PROCS=ss-local/PROCS=ss-redir/" -i  $CHECK/init.d/S22shadowsocks

		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S27pcap_dnsproxy (start))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks
		sed -i 's/^#\([ \t]\+iptables -t nat -I PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 5353\)/\1/' $PREFIX/shadowsocks/shadowsocks
	
		local_dns=`cat /etc/resolv.dnsmasq | awk '/^nameserver/{print $2}' | sed -n '1p'`
		sed -i "s/ 114.114.115.115:53/ $local_dns:53/" $CHECK/pcap-dnsproxy/Config.conf
		
		touch $PREFIX/shadowsocks/update.lock
		touch $PREFIX/shadowsocks/chnroutes.lock
		touch /var/log/pcap_dnsproxy.lock
		$PREFIX/shadowsocks/shadowsocks modules
		sleep 4
		$PREFIX/shadowsocks/shadowsocks run
		sleep 2
		$PREFIX/shadowsocks/shadowsocks rules

		echo -e $INFO Configuring ntp server...
		cat /etc/resolv.dnsmasq | awk '/^nameserver/{print $2}' > $PREFIX/shadowsocks/dns.list
		DNS=`sed -n '1p' $PREFIX/shadowsocks/dns.list`
		NTP=$PREFIX/shadowsocks/dnsmasq.d/ntp_server.conf
		echo "server=/0.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/1.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/2.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/3.asia.pool.ntp.org/$DNS" >> $NTP
		echo >> $NTP
		rm -f $PREFIX/shadowsocks/dns.list

		nvram set time_zone="Asia/Shanghai"		

		echo -e $INFO Configuring dnsmasq_custom...		
		echo -e "no-resolv \nno-poll \nserver=127.0.0.1#5353 \nall-servers \nproxy-dnssec \nmin-cache-ttl=6000 \ncache-size=10000 \nconf-dir=$PREFIX/shadowsocks/dnsmasq.d" > /var/log/dnsmasq_custom.txt
		DNS_CUSTOM=`sed -e '' /var/log/dnsmasq_custom.txt`
		nvram set dnsmasq_options="$DNS_CUSTOM"	
		
		echo -e $INFO Configuring turn startup items and guard the capital...
		echo -e "$PREFIX/opt/etc/init.d/auto.run" > /var/log/scr_c.txt
		SCR=`sed -e '' /var/log/scr_c.txt`
		nvram set rc_startup="$SCR"
		nvram commit
	
		echo -e "echo \"\" > /var/log/shadowsocks_watchdog.log \necho \"\" > /var/log/Pcap_DNSProxy_watchdog.log \necho \"\" > /var/log/iptables_rules.log" > $CHECK/cron.5mins/clear_log.sh
#		echo 'iptables-save | grep -E "SS_SPEC|ADM_|WANPREROUTING|POSTROUTING|^\*nat" > /var/log/iptables-restore.log' > $CHECK/cron.5mins/iptables_restore.sh		
		echo -e "shadowsocks check \nshadowsocks check_rules" > $CHECK/cron.1min/check.sh			

#		shadowsocks temp
#		
		rm -f $PREFIX/shadowsocks/update.lock
		rm -f $PREFIX/shadowsocks/chnroutes.lock
		echo -e "$BOLD Set successfully, please reboot the router. $NORM"		
		echo -e "$ansi_red Set successfully, please reboot the router. Found a Bug? Plea se report at https://github.com/houzi-/tomato-shadowsocks/issues. $ansi_std"
		killall shadowsocks > /dev/null
	elif [ $programs == "5" ];then
		echo -e "$BOLD Set programs_5..." $NORM
		sed -e "s/shadowsocks.json\"/shadowsocks.json\"/" -e "s/PROCS=ss-local/PROCS=ss-redir/" -i  $CHECK/init.d/S22shadowsocks
		sed -e "s/shadowsocks.json\"/shadowsocks.json -b 0.0.0.0 -l 5300 -L 8.8.8.8:53 -u\"/" -e "s/PROCS=ss-redir/PROCS=ss-tunnel/" $CHECK/init.d/S22shadowsocks > $CHECK/init.d/S23ss-tunnel
		sed '4c PROCS=chinadns' $CHECK/init.d/S22shadowsocks > $CHECK/init.d/S24cn
		sed '5c ARGS="-p 5353 -l /opt/etc/chinadns_iplist.txt -c /opt/etc/chnroute.txt -s 114.114.114.114,127.0.0.1:5300"' $CHECK/init.d/S24cn > $CHECK/init.d/S24chinadns
		
		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S23ss-tunnel (start|restart))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks
		sed -r 's/#(['$'\t'' ]*\/opt\/etc\/init.d\/S24chinadns (start|restart))/\1/' $PREFIX/shadowsocks/shadowsocks -i $PREFIX/shadowsocks/shadowsocks	

		CHINADNS=`nvram get wan_get_dns | sed 's/ /,/'`
		sed -i "s/^ARGS=\(.*\)114.114.114.114\(.*\)$/ARGS=\1$CHINADNS\2/" $CHECK/init.d/S24chinadns
	
		rm -f $CHECK/init.d/S24cn
		chmod +x $CHECK/init.d/S2*	
			
		touch $PREFIX/shadowsocks/update.lock
		touch $PREFIX/shadowsocks/chnroutes.lock
		$PREFIX/shadowsocks/shadowsocks modules
		sleep 4
		$PREFIX/shadowsocks/shadowsocks run
		sleep 2
		$PREFIX/shadowsocks/shadowsocks rules

		echo -e $INFO Configuring ntp server...
		cat /etc/resolv.dnsmasq | awk '/^nameserver/{print $2}' > $PREFIX/shadowsocks/dns.list
		DNS=`sed -n '1p' $PREFIX/shadowsocks/dns.list`
		NTP=$PREFIX/shadowsocks/dnsmasq.d/ntp_server.conf
		echo "server=/0.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/1.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/2.asia.pool.ntp.org/$DNS" >> $NTP
		echo "server=/3.asia.pool.ntp.org/$DNS" >> $NTP
		echo >> $NTP
		rm -f $PREFIX/shadowsocks/dns.list

		nvram set time_zone="Asia/Shanghai"		
		
		echo -e $INFO Configuring dnsmasq_custom...		
		echo -e "no-resolv \nno-poll \nserver=127.0.0.1#5353 \nall-servers \nmin-cache-ttl=6000 \ncache-size=10000 \nconf-dir=$PREFIX/shadowsocks/dnsmasq.d" > /var/log/dnsmasq_custom.txt
		DNS_CUSTOM=`sed -e '' /var/log/dnsmasq_custom.txt`
		nvram set dnsmasq_options="$DNS_CUSTOM"		

		echo -e $INFO Configuring turn startup items and guard the capital...
		echo -e "$PREFIX/opt/etc/init.d/auto.run" > /var/log/scr_c.txt
		SCR=`sed -e '' /var/log/scr_c.txt`
		nvram set rc_startup="$SCR"
		nvram commit
	
		echo -e "echo \"\" > /var/log/shadowsocks_watchdog.log \necho \"\" > /var/log/chinadns.log \necho \"\" > /var/log/iptables_rules.log" > $CHECK/cron.5mins/clear_log.sh
#		echo 'iptables-save | grep -E "SS_SPEC|ADM_|WANPREROUTING|POSTROUTING|^\*nat" > /var/log/iptables-restore.log' > $CHECK/cron.5mins/iptables_restore.sh		
		echo -e "shadowsocks check \nshadowsocks check_rules" > $CHECK/cron.1min/check.sh			

#		shadowsocks temp
#		
		rm -f $PREFIX/shadowsocks/update.lock
		rm -f $PREFIX/shadowsocks/chnroutes.lock
		echo -e "$BOLD Set successfully, please reboot the router. $NORM"		
		echo -e "$ansi_red Set successfully, please reboot the router. Found a Bug? Plea se report at https://github.com/houzi-/tomato-shadowsocks/issues. $ansi_std"
		killall shadowsocks > /dev/null
	fi	
	;;	

"modules" )
	insmod /opt/lib/modules/xt_set.ko
	;;
	
"run" )
	sed -n 's/.*ver":"\(.*\)".*/\1/p' $CHECK/shadowsocks.json  > /var/log/server.txt
	
	if [ -f "$PREFIX/shadowsocks/chnroutes.lock" ]; then
		$PREFIX/shadowsocks/shadowsocks update
	else
		echo '['$DATE'] Has loaded China route table.' > /var/log/chnroutes.log
	fi
	
	PROCESS=$(ps | grep "ss-redir" | grep -v "grep")
	if [ -z "$PROCESS" ]; then
		mount -o bind /opt/sbin/dnsmasq /usr/sbin/dnsmasq && /opt/etc/init.d/S56dnsmasq restart
		mount -o bind /opt/sbin/iptables /usr/sbin/iptables
		/opt/etc/init.d/S22shadowsocks start && touch /var/log/shadowsocks.lock
#		/opt/etc/init.d/S23ss-tunnel start && touch /var/log/ss-tunnel.lock
#		/opt/etc/init.d/S26pdnsd start && touch /var/log/pdnsd.lock
#		/opt/etc/init.d/S24chinadns start && touch /var/log/chinadns.lock
#		/opt/etc/init.d/S27pcap_dnsproxy start && touch /var/log/pcap_dnsproxy.lock
#		/opt/etc/init.d/S29dnscrypt-proxy start && touch /var/log/dnscrypt-proxy.lock
		/opt/etc/init.d/S00timezone start
		/opt/etc/init.d/S10cron start
		exit 0	
	else
		for i in `cat /var/log/server.txt`;do
        		for j in `cat $PREFIX/opt/var/log/server.txt`;do
                		if [ $i == $j ]; then
					echo "$(date): OK" >> /var/log/account_switching.log
				else
					/opt/etc/init.d/S22shadowsocks restart
#					/opt/etc/init.d/S23ss-tunnel restart
					rm -f $PREFIX/shadowsocks/flush.lock
					$PREFIX/shadowsocks/shadowsocks flush
					sleep 2
					$PREFIX/shadowsocks/shadowsocks rules
				fi
			done
		done
	fi
	;;
	
"rules" )
	sed -n 's/.*ver":"\(.*\)".*/\1/p' $CHECK/shadowsocks.json  > $PREFIX/opt/var/log/server.txt
	/opt/etc/init.d/S99ss-rules start
	sleep 1
	iptables -t nat -I SS_SPEC_WAN_AC 1 -d `nvram get wan_ipaddr` -j RETURN	
	nvram get wan_ipaddr > /var/log/wan_ipaddr.log
	;;
	
"flush" )
	ss-rules -f
	;;

"check" )
	SHADOWSOCKS=$(ps | grep "ss-redir" | grep -v "grep")
	if [ -f "/var/log/shadowsocks.lock" ]; then
		if [ -z "$SHADOWSOCKS" ]; then
        		echo '['$DATE'] Shadowsoks abnormal operation, restarting shadowsocks.' >> /var/log/shadowsocks_watchdog.log 2>&1
			/opt/etc/init.d/S22shadowsocks start
		else
      			echo '['$DATE'] No problem, the normal operation of shadowsoks.' >> /var/log/shadowsocks_watchdog.log 2>&1
		fi
	fi		
	
	dnscrypt=$(ps | grep "dnscrypt-proxy" | grep -v "grep")
	if [ -f "/var/log/dnscrypt-proxy.lock" ]; then
		if [ -z "$dnscrypt" ]; then
			echo '['$DATE'] dnscrypt-proxy abnormal operation, restarting dnscrypt-proxy.' >> /var/log/dnscrypt-proxy_watchdog.log 2>&1
#			/opt/etc/init.d/S29dnscrypt-proxy start
		else
			echo '['$DATE'] No problem, the normal operation of dnscrypt-proxy.' >> /var/log/dnscrypt-proxy_watchdog.log 2>&1
		fi
	fi	
	
	Pcap_DNSProxy=$(ps | grep "Pcap_DNSProxy" | grep -v "grep")
	if [ -f "/var/log/pcap_dnsproxy.lock" ]; then
		if [ -z "$Pcap_DNSProxy" ]; then
			echo '['$DATE'] Pcap_DNSProxy abnormal operation, restarting Pcap_DNSProxy.' >> /var/log/Pcap_DNSProxy_watchdog.log 2>&1
#			/opt/etc/init.d/S27pcap_dnsproxy start
		else
			echo '['$DATE'] No problem, the normal operation of Pcap_DNSProxy.' >> /var/log/Pcap_DNSProxy_watchdog.log 2>&1
		fi
	fi

	PDNSD=$(ps | grep "pdnsd" | grep -v "grep")
	if [ -f "/var/log/pdnsd.lock" ]; then	
		if [ -z "$PDNSD" ]; then
			echo '['$DATE'] Pdnsd abnormal operation, restarting pdnsd.' >> /var/log/pdnsd_watchdog.log 2>&1
#			/opt/etc/init.d/S26pdnsd start
		else
			echo '['$DATE'] No problem, the normal operation of pdnsd.' >> /var/log/pdnsd_watchdog.log 2>&1
		fi
	fi	

	OLD_WAN_IP=`cat /var/log/wan_ipaddr.log`
	if [ ! $OLD_WAN_IP == `nvram get wan_ppp_get_ip` ]; then
		iptables -t nat -D SS_SPEC_WAN_AC -d `cat /var/log/wan_ipaddr.log` -j RETURN	
		iptables -t nat -I SS_SPEC_WAN_AC 1 -d `nvram get wan_ipaddr` -j RETURN
		nvram get wan_ipaddr > /var/log/wan_ipaddr.log
	fi
	
	judge=$(cd $PREFIX/shadowsocks && ls | grep "ignore.list" | grep -v "grep")
	if [ -z "$judge" ]; then
		exit 0
	else
		CHINADNS=$(ps | grep "chinadns" | grep -v "grep")
		if [ -f "/var/log/chinadns.lock" ]; then
			if [ -z "$CHINADNS" ]; then
				echo '['$DATE'] ChinaDNS is restarting.' >> /var/log/chinadns_watchdog.log 2>&1
#				/opt/etc/init.d/S24chinadns start
			else
				echo '['$DATE'] ChinaDNS no problem.' >> /var/log/chinadns_watchdog.log 2>&1
			fi
		fi
	fi		
	;;	
		
*)
	echo -e "$ansi_green # ------------------------------------------------------------------- $ansi_std"
	echo -e "$ansi_green # Copyright (C) 2016 Jason Lin <wojiaolinmu008@gmail.com> $ansi_std"
	echo -e "$ansi_green # Last edited: 2016.4.20 $ansi_std"
	echo -e "$ansi_green # Version: V1.0-1 (ARM beta version) $ansi_std"
	echo -e "$ansi_green # Explain: This script can be used only for DD-WRT ARM firmware. $ansi_std"
	echo -e "$ansi_green # Thanks: [@aa65535 @wojiaolinmu008 @tomato_shibby @asus_merlin @bwq518] $ansi_std"
	echo -e "$ansi_green # Description: This is a science on ShadowSocks Internet automatic $ansi_std"
	echo -e "$ansi_green # configuration script in DD-WRT under$ansi_std. "
	echo -e "$ansi_green # This is free software, licensed under the GNU General Public License v3. $ansi_std"
	echo -e "$ansi_green # See /LICENSE for more information. $ansi_std"
	echo -e "$ansi_green # ------------------------------------------------------------------- $ansi_std"
	echo -e "$ansi_white ===================================================================== $ansi_std"
	echo -e "$ansi_blue WIKI: $ansi_std"
	echo -e "$ansi_white   [set_up] Set ShadowSocks and ChinaDNS $ansi_std"
	echo -e "$ansi_white   [modules] Loading module and ipset rule $ansi_std"
	echo -e "$ansi_white   [run] Running ShadowSocks and ChinaDNS $ansi_std"	
	echo -e "$ansi_white   [rules] Application Firewall Policy $ansi_std"
	echo -e "$ansi_white   [global] Global Proxy $ansi_std"
	echo -e "$ansi_white   [flush] Clear firewall policy $ansi_std"
	echo -e "$ansi_white   [update] Update chnroutes Routing Host $ansi_std"
	echo -e "$ansi_white   [update_gfwlist] Update GFWLIST domain $ansi_std"
	echo -e "$ansi_white   [check] Guardian ss-redir* $ansi_std"
	echo -e "$ansi_white   [check_rules] Guardian iptables rules $ansi_std"
	echo -e "$ansi_white   [ss_switch] Account switching $ansi_std"
	echo -e "$ansi_white   [mult_switch] Multiple_switching $ansi_std"
	echo -e "$ansi_white   [lan_ignore] LAN access control $ansi_std"
	echo -e "$ansi_white   [off_on] Turn off switch $ansi_std"
	echo -e "$ansi_white   [update_scr] Update script $ansi_std"
	echo -e "$ansi_white   [rebuild_scr] Rebuild script $ansi_std"	
	echo -e "$ansi_white   [mail] Send shadowsocks running information $ansi_std"
	echo -e "$ansi_white   [help] Script help $ansi_std"
	echo -e "$ansi_white ===================================================================== $ansi_std"
	exit 
	;;
esac